// <auto-generated> by src/LibcameraSharp.Core/Generate/gen_pinvoke.py from src/LibcameraSharp.Native/c_api — do not edit. </auto-generated>
#nullable enable

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace LibcameraSharp.Native.Interop;

#pragma warning disable CS1591, IDE1006 // generated: verbatim C names

internal static unsafe partial class NativeMethods
{
    internal const string LibraryName = "libcamera-shim";
    /// <summary>libcamera headers these bindings were generated against.</summary>
    internal const string GeneratedAgainstLibcamera = "0.7.2";

    // ---- camera.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_acquire")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_camera_acquire(libcamera_camera_t* cam);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_buffer_completed_connect")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_callback_handle* libcamera_camera_buffer_completed_connect(libcamera_camera_t* cam, delegate* unmanaged[Cdecl]<void*, libcamera_request*, libcamera_framebuffer*, void> callback, void* data);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_buffer_completed_disconnect")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_camera_buffer_completed_disconnect(libcamera_camera_t* cam, libcamera_callback_handle* handle);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_configuration_add_configuration")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_stream_configuration* libcamera_camera_configuration_add_configuration(libcamera_camera_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_configuration_add_configuration_from")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_stream_configuration* libcamera_camera_configuration_add_configuration_from(libcamera_camera_configuration_t* config, libcamera_stream_configuration* src);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_configuration_at")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_stream_configuration* libcamera_camera_configuration_at(libcamera_camera_configuration_t* config, nuint index);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_configuration_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_camera_configuration_destroy(libcamera_camera_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_configuration_get_orientation")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_orientation libcamera_camera_configuration_get_orientation(libcamera_camera_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_configuration_get_sensor_configuration")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_sensor_configuration_t* libcamera_camera_configuration_get_sensor_configuration(libcamera_camera_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_configuration_set_orientation")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_camera_configuration_set_orientation(libcamera_camera_configuration_t* config, libcamera_orientation orientation);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_configuration_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_camera_configuration_size(libcamera_camera_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_configuration_to_string", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial string? libcamera_camera_configuration_to_string(libcamera_camera_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_configuration_validate")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_camera_configuration_status libcamera_camera_configuration_validate(libcamera_camera_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_configure")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_camera_configure(libcamera_camera_t* cam, libcamera_camera_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_controls")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_info_map* libcamera_camera_controls(libcamera_camera_t* cam);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_copy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_camera_t* libcamera_camera_copy(libcamera_camera_t* cam);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_create_request")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_request* libcamera_camera_create_request(libcamera_camera_t* cam, ulong cookie);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_camera_destroy(libcamera_camera_t* cam);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_disconnected_connect")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_callback_handle* libcamera_camera_disconnected_connect(libcamera_camera_t* cam, delegate* unmanaged[Cdecl]<void*, void> callback, void* data);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_disconnected_disconnect")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_camera_disconnected_disconnect(libcamera_camera_t* cam, libcamera_callback_handle* handle);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_generate_configuration")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_camera_configuration_t* libcamera_camera_generate_configuration(libcamera_camera_t* cam, libcamera_stream_role* roles, nuint role_count);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_id", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalUsing(typeof(BorrowedUtf8StringMarshaller))] internal static partial string? libcamera_camera_id(libcamera_camera_t* cam);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_properties")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_list* libcamera_camera_properties(libcamera_camera_t* cam);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_queue_request")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_camera_queue_request(libcamera_camera_t* cam, libcamera_request* request);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_release")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_camera_release(libcamera_camera_t* cam);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_request_completed_connect")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_callback_handle* libcamera_camera_request_completed_connect(libcamera_camera_t* cam, delegate* unmanaged[Cdecl]<void*, libcamera_request*, void> callback, void* data);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_request_completed_disconnect")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_camera_request_completed_disconnect(libcamera_camera_t* cam, libcamera_callback_handle* handle);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_set_sensor_configuration")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_camera_set_sensor_configuration(libcamera_camera_configuration_t* config, libcamera_sensor_configuration_t* sensor_config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_start")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_camera_start(libcamera_camera_t* cam, libcamera_control_list* controls);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_stop")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_camera_stop(libcamera_camera_t* cam);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_streams")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_stream_set* libcamera_camera_streams(libcamera_camera_t* cam);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_create")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_sensor_configuration_t* libcamera_sensor_configuration_create();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_sensor_configuration_destroy(libcamera_sensor_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_get_analog_crop")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_rectangle libcamera_sensor_configuration_get_analog_crop(libcamera_sensor_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_get_binning")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_sensor_configuration_get_binning(libcamera_sensor_configuration_t* config, uint* x, uint* y);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_get_bit_depth")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial uint libcamera_sensor_configuration_get_bit_depth(libcamera_sensor_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_get_output_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_size libcamera_sensor_configuration_get_output_size(libcamera_sensor_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_get_skipping")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_sensor_configuration_get_skipping(libcamera_sensor_configuration_t* config, uint* x_odd_inc, uint* x_even_inc, uint* y_odd_inc, uint* y_even_inc);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_is_valid")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_sensor_configuration_is_valid(libcamera_sensor_configuration_t* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_set_analog_crop")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_sensor_configuration_set_analog_crop(libcamera_sensor_configuration_t* config, libcamera_rectangle* crop);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_set_binning")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_sensor_configuration_set_binning(libcamera_sensor_configuration_t* config, uint x, uint y);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_set_bit_depth")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_sensor_configuration_set_bit_depth(libcamera_sensor_configuration_t* config, uint bit_depth);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_set_output_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_sensor_configuration_set_output_size(libcamera_sensor_configuration_t* config, uint width, uint height);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sensor_configuration_set_skipping")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_sensor_configuration_set_skipping(libcamera_sensor_configuration_t* config, uint x_odd_inc, uint x_even_inc, uint y_odd_inc, uint y_even_inc);

    // ---- camera_manager.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_list_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_camera_list_destroy(libcamera_camera_list_t* list);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_list_get")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_camera_t* libcamera_camera_list_get(libcamera_camera_list_t* list, nuint index);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_list_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_camera_list_size(libcamera_camera_list_t* list);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_manager_camera_added_connect")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_callback_handle* libcamera_camera_manager_camera_added_connect(libcamera_camera_manager_t* mgr, delegate* unmanaged[Cdecl]<void*, libcamera_camera_t*, void> callback, void* data);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_manager_camera_removed_connect")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_callback_handle* libcamera_camera_manager_camera_removed_connect(libcamera_camera_manager_t* mgr, delegate* unmanaged[Cdecl]<void*, libcamera_camera_t*, void> callback, void* data);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_manager_camera_signal_disconnect")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_camera_manager_camera_signal_disconnect(libcamera_camera_manager_t* mgr, libcamera_callback_handle* handle);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_manager_cameras")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_camera_list_t* libcamera_camera_manager_cameras(libcamera_camera_manager_t* mgr);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_manager_create")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_camera_manager_t* libcamera_camera_manager_create();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_manager_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_camera_manager_destroy(libcamera_camera_manager_t* mgr);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_manager_get_id", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_camera_t* libcamera_camera_manager_get_id(libcamera_camera_manager_t* mgr, string id);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_manager_start")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_camera_manager_start(libcamera_camera_manager_t* mgr);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_manager_stop")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_camera_manager_stop(libcamera_camera_manager_t* mgr);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_camera_manager_version", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalUsing(typeof(BorrowedUtf8StringMarshaller))] internal static partial string? libcamera_camera_manager_version(libcamera_camera_manager_t* mgr);

    // ---- color_space.h ----

    /// <summary>
    /// Adjust color space to a pixel format; returns true if adjusted/valid.
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "libcamera_color_space_adjust")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_color_space_adjust(libcamera_color_space* color_space, libcamera_pixel_format* pixel_format);

    /// <summary>
    /// Convert string to ColorSpace; returns true on success and writes result.
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "libcamera_color_space_from_string", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_color_space_from_string(string str, libcamera_color_space* @out);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_color_space_make")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_color_space libcamera_color_space_make(libcamera_color_space_primaries primaries, libcamera_color_space_transfer_function tf, libcamera_color_space_ycbcr_encoding ycbcr, libcamera_color_space_range range);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_color_space_raw")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_color_space libcamera_color_space_raw();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_color_space_rec2020")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_color_space libcamera_color_space_rec2020();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_color_space_rec709")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_color_space libcamera_color_space_rec709();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_color_space_smpte170m")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_color_space libcamera_color_space_smpte170m();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_color_space_srgb")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_color_space libcamera_color_space_srgb();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_color_space_sycc")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_color_space libcamera_color_space_sycc();

    /// <summary>
    /// Converts ColorSpace to string (std::string::c_str())
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "libcamera_color_space_to_string", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial string? libcamera_color_space_to_string(libcamera_color_space* color_space);

    // ---- controls.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_from_id")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_id* libcamera_control_from_id(libcamera_control_id_enum id);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_id_enum libcamera_control_id(libcamera_control_id* control);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_direction")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_direction libcamera_control_id_direction(libcamera_control_id* control);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_enumerators_iter_create")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_id_enumerators_iter* libcamera_control_id_enumerators_iter_create(libcamera_control_id* control);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_enumerators_iter_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_id_enumerators_iter_destroy(libcamera_control_id_enumerators_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_enumerators_iter_has_next")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_control_id_enumerators_iter_has_next(libcamera_control_id_enumerators_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_enumerators_iter_key")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_control_id_enumerators_iter_key(libcamera_control_id_enumerators_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_enumerators_iter_next")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_id_enumerators_iter_next(libcamera_control_id_enumerators_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_enumerators_iter_value", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalUsing(typeof(BorrowedUtf8StringMarshaller))] internal static partial string? libcamera_control_id_enumerators_iter_value(libcamera_control_id_enumerators_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_is_array")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_control_id_is_array(libcamera_control_id* control);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_is_input")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_control_id_is_input(libcamera_control_id* control);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_is_output")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_control_id_is_output(libcamera_control_id* control);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_map_add")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_control_id_map_add(libcamera_control_id_map* idmap, uint key, libcamera_control_id* control_id);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_map_get")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_id* libcamera_control_id_map_get(libcamera_control_id_map* idmap, uint key);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_map_iter_create")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_id_map_iter* libcamera_control_id_map_iter_create(libcamera_control_id_map* map);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_map_iter_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_id_map_iter_destroy(libcamera_control_id_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_map_iter_has_next")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_control_id_map_iter_has_next(libcamera_control_id_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_map_iter_key")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial uint libcamera_control_id_map_iter_key(libcamera_control_id_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_map_iter_next")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_id_map_iter_next(libcamera_control_id_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_map_iter_value")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_id* libcamera_control_id_map_iter_value(libcamera_control_id_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_control_id_size(libcamera_control_id* control);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_type")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_type libcamera_control_id_type(libcamera_control_id* control);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_id_vendor", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalUsing(typeof(BorrowedUtf8StringMarshaller))] internal static partial string? libcamera_control_id_vendor(libcamera_control_id* control);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_def")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_value* libcamera_control_info_def(libcamera_control_info* val);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_map_at")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_info* libcamera_control_info_map_at(libcamera_control_info_map* map, uint key);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_map_count")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_control_info_map_count(libcamera_control_info_map* map, uint key);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_map_find")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_info* libcamera_control_info_map_find(libcamera_control_info_map* map, uint key);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_map_iter_create")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_info_map_iter* libcamera_control_info_map_iter_create(libcamera_control_info_map* map);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_map_iter_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_info_map_iter_destroy(libcamera_control_info_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_map_iter_has_next")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_control_info_map_iter_has_next(libcamera_control_info_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_map_iter_key")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial uint libcamera_control_info_map_iter_key(libcamera_control_info_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_map_iter_next")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_info_map_iter_next(libcamera_control_info_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_map_iter_value")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_info* libcamera_control_info_map_iter_value(libcamera_control_info_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_map_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_control_info_map_size(libcamera_control_info_map* map);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_max")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_value* libcamera_control_info_max(libcamera_control_info* val);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_min")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_value* libcamera_control_info_min(libcamera_control_info* val);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_info_values")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_value* libcamera_control_info_values(libcamera_control_info* info, nuint* size);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_clear")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_list_clear(libcamera_control_list* list);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_contains")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_control_list_contains(libcamera_control_list* list, uint id);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_create")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_list* libcamera_control_list_create();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_create_with_idmap")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_list* libcamera_control_list_create_with_idmap(libcamera_control_id_map* idmap);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_create_with_info_map")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_list* libcamera_control_list_create_with_info_map(libcamera_control_info_map* info_map);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_list_destroy(libcamera_control_list* list);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_get")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_value* libcamera_control_list_get(libcamera_control_list* list, libcamera_property_id id);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_id_map")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_id_map* libcamera_control_list_id_map(libcamera_control_list* list);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_info_map")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_info_map* libcamera_control_list_info_map(libcamera_control_list* list);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_is_empty")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_control_list_is_empty(libcamera_control_list* list);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_iter")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_list_iter* libcamera_control_list_iter(libcamera_control_list* list);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_iter_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_list_iter_destroy(libcamera_control_list_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_iter_end")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_control_list_iter_end(libcamera_control_list_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_iter_id")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial uint libcamera_control_list_iter_id(libcamera_control_list_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_iter_next")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_list_iter_next(libcamera_control_list_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_iter_value")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_value* libcamera_control_list_iter_value(libcamera_control_list_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_merge")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_list_merge(libcamera_control_list* list, libcamera_control_list* other, libcamera_control_merge_policy policy);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_set")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_list_set(libcamera_control_list* list, libcamera_property_id id, libcamera_control_value* val);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_list_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_control_list_size(libcamera_control_list* list);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_name", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalUsing(typeof(BorrowedUtf8StringMarshaller))] internal static partial string? libcamera_control_name(libcamera_control_id* control);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_name_from_id", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalUsing(typeof(BorrowedUtf8StringMarshaller))] internal static partial string? libcamera_control_name_from_id(libcamera_control_id_enum id);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_type_from_id")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_type libcamera_control_type_from_id(libcamera_control_id_enum id);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_value_create")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_value* libcamera_control_value_create();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_value_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_value_destroy(libcamera_control_value* val);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_value_get")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void* libcamera_control_value_get(libcamera_control_value* val);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_value_is_array")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_control_value_is_array(libcamera_control_value* val);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_value_is_none")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_control_value_is_none(libcamera_control_value* val);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_value_num_elements")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_control_value_num_elements(libcamera_control_value* val);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_value_set")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_control_value_set(libcamera_control_value* val, libcamera_control_type type, void* data, [MarshalAs(UnmanagedType.U1)] bool is_array, nuint num_elements);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_value_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_control_value_size();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_control_value_type")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_type libcamera_control_value_type(libcamera_control_value* val);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_property_name_from_id", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalUsing(typeof(BorrowedUtf8StringMarshaller))] internal static partial string? libcamera_property_name_from_id(libcamera_property_id id);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_property_type_from_id")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_type libcamera_property_type_from_id(libcamera_property_id id);

    // ---- fence.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_fence_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_fence_destroy(libcamera_fence* fence);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_fence_fd")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_fence_fd(libcamera_fence* fence);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_fence_from_fd")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_fence* libcamera_fence_from_fd(int fd);

    // ---- framebuffer.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_frame_metadata_planes")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_frame_metadata_planes* libcamera_frame_metadata_planes(libcamera_frame_metadata* metadata);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_frame_metadata_planes_at")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_frame_metadata_plane* libcamera_frame_metadata_planes_at(libcamera_frame_metadata_planes* planes, nuint index);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_frame_metadata_planes_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_frame_metadata_planes_destroy(libcamera_frame_metadata_planes* planes);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_frame_metadata_planes_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_frame_metadata_planes_size(libcamera_frame_metadata_planes* planes);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_frame_metadata_sequence")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial uint libcamera_frame_metadata_sequence(libcamera_frame_metadata* metadata);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_frame_metadata_status")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_frame_metadata_status libcamera_frame_metadata_status(libcamera_frame_metadata* metadata);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_frame_metadata_timestamp")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial ulong libcamera_frame_metadata_timestamp(libcamera_frame_metadata* metadata);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_cookie")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial ulong libcamera_framebuffer_cookie(libcamera_framebuffer* framebuffer);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_create")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_framebuffer* libcamera_framebuffer_create(libcamera_framebuffer_plane_info* planes, nuint num_planes, ulong cookie);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_framebuffer_destroy(libcamera_framebuffer* framebuffer);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_metadata")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_frame_metadata* libcamera_framebuffer_metadata(libcamera_framebuffer* framebuffer);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_plane_fd")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_framebuffer_plane_fd(libcamera_framebuffer_plane* plane);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_plane_length")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_framebuffer_plane_length(libcamera_framebuffer_plane* plane);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_plane_offset")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_framebuffer_plane_offset(libcamera_framebuffer_plane* plane);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_plane_offset_valid")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_framebuffer_plane_offset_valid(libcamera_framebuffer_plane* plane);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_planes")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_framebuffer_planes* libcamera_framebuffer_planes(libcamera_framebuffer* framebuffer);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_planes_at")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_framebuffer_plane* libcamera_framebuffer_planes_at(libcamera_framebuffer_planes* planes, nuint index);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_planes_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_framebuffer_planes_destroy(libcamera_framebuffer_planes* planes);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_planes_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_framebuffer_planes_size(libcamera_framebuffer_planes* planes);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_release_fence")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_framebuffer_release_fence(libcamera_framebuffer* framebuffer);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_release_fence_handle")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_fence* libcamera_framebuffer_release_fence_handle(libcamera_framebuffer* framebuffer);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_request")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_request* libcamera_framebuffer_request(libcamera_framebuffer* framebuffer);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_set_cookie")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_framebuffer_set_cookie(libcamera_framebuffer* framebuffer, ulong cookie);

    // ---- framebuffer_allocator.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_allocator_allocate")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_framebuffer_allocator_allocate(libcamera_framebuffer_allocator* alloc, libcamera_stream* stream);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_allocator_allocated")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_framebuffer_allocator_allocated(libcamera_framebuffer_allocator* alloc);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_allocator_buffers")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_framebuffer_list* libcamera_framebuffer_allocator_buffers(libcamera_framebuffer_allocator* alloc, libcamera_stream* stream);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_allocator_create")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_framebuffer_allocator* libcamera_framebuffer_allocator_create(libcamera_camera_t* cam);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_allocator_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_framebuffer_allocator_destroy(libcamera_framebuffer_allocator* alloc);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_allocator_free")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_framebuffer_allocator_free(libcamera_framebuffer_allocator* alloc, libcamera_stream* stream);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_list_get")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_framebuffer* libcamera_framebuffer_list_get(libcamera_framebuffer_list* list, nuint index);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_framebuffer_list_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_framebuffer_list_size(libcamera_framebuffer_list* list);

    // ---- geometry.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sizes_at")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_size* libcamera_sizes_at(libcamera_sizes* sizes, nuint index);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sizes_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_sizes_destroy(libcamera_sizes* sizes);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_sizes_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_sizes_size(libcamera_sizes* sizes);

    // ---- logging.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_log_set_custom_stream")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_log_set_custom_stream(void* ostream, [MarshalAs(UnmanagedType.U1)] bool color);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_log_set_file", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_log_set_file(string path, [MarshalAs(UnmanagedType.U1)] bool color);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_log_set_level", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_log_set_level(string category, string level);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_log_set_stream")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_log_set_stream(libcamera_logging_stream stream, [MarshalAs(UnmanagedType.U1)] bool color);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_log_set_target")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_log_set_target(libcamera_logging_target target);

    // ---- pixel_format.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_pixel_format_from_str", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_pixel_format libcamera_pixel_format_from_str(string name);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_pixel_format_is_valid")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_pixel_format_is_valid(libcamera_pixel_format* format);

    /// <summary>
    /// @brief Converts pixel format to a human readable string representation
    /// @param format libcamera PixelFormat structure
    /// @return A heap allocated null-terminated string, that has to be deallocated with free()
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "libcamera_pixel_format_str", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial string? libcamera_pixel_format_str(libcamera_pixel_format* format);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_pixel_formats_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_pixel_formats_destroy(libcamera_pixel_formats* formats);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_pixel_formats_get")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_pixel_format libcamera_pixel_formats_get(libcamera_pixel_formats* formats, nuint index);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_pixel_formats_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_pixel_formats_size(libcamera_pixel_formats* formats);

    // ---- request.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_add_buffer")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_request_add_buffer(libcamera_request* request, libcamera_stream* stream, libcamera_framebuffer* buffer);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_add_buffer_with_fence")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int libcamera_request_add_buffer_with_fence(libcamera_request* request, libcamera_stream* stream, libcamera_framebuffer* buffer, libcamera_fence* fence);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_buffer_map_get")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_framebuffer* libcamera_request_buffer_map_get(libcamera_request_buffer_map* buffer_map, libcamera_stream* stream);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_buffer_map_iter")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_request_buffer_map_iter* libcamera_request_buffer_map_iter(libcamera_request_buffer_map* buffer_map);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_buffer_map_iter_buffer")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_framebuffer* libcamera_request_buffer_map_iter_buffer(libcamera_request_buffer_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_buffer_map_iter_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_request_buffer_map_iter_destroy(libcamera_request_buffer_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_buffer_map_iter_end")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_request_buffer_map_iter_end(libcamera_request_buffer_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_buffer_map_iter_next")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_request_buffer_map_iter_next(libcamera_request_buffer_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_buffer_map_iter_stream")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_stream* libcamera_request_buffer_map_iter_stream(libcamera_request_buffer_map_iter* iter);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_buffers")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_request_buffer_map* libcamera_request_buffers(libcamera_request* request);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_controls")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_list* libcamera_request_controls(libcamera_request* request);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_cookie")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial ulong libcamera_request_cookie(libcamera_request* request);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_request_destroy(libcamera_request* request);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_find_buffer")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_framebuffer* libcamera_request_find_buffer(libcamera_request* request, libcamera_stream* stream);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_has_pending_buffers")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_request_has_pending_buffers(libcamera_request* request);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_metadata")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_control_list* libcamera_request_metadata(libcamera_request* request);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_reuse")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_request_reuse(libcamera_request* request, libcamera_request_reuse_flag flags);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_sequence")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial uint libcamera_request_sequence(libcamera_request* request);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_status")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_request_status libcamera_request_status(libcamera_request* request);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_request_to_string", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial string? libcamera_request_to_string(libcamera_request* request);

    // ---- stream.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_configuration_formats")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_stream_formats* libcamera_stream_configuration_formats(libcamera_stream_configuration* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_configuration_get_color_space")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_color_space libcamera_stream_configuration_get_color_space(libcamera_stream_configuration* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_configuration_has_color_space")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.U1)] internal static partial bool libcamera_stream_configuration_has_color_space(libcamera_stream_configuration* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_configuration_set_color_space")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_stream_configuration_set_color_space(libcamera_stream_configuration* config, libcamera_color_space* color_space);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_configuration_stream")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_stream* libcamera_stream_configuration_stream(libcamera_stream_configuration* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_configuration_to_string", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial string? libcamera_stream_configuration_to_string(libcamera_stream_configuration* config);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_formats_pixel_formats")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_pixel_formats* libcamera_stream_formats_pixel_formats(libcamera_stream_formats* formats);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_formats_range")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_size_range libcamera_stream_formats_range(libcamera_stream_formats* formats, libcamera_pixel_format* pixel_format);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_formats_sizes")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_sizes* libcamera_stream_formats_sizes(libcamera_stream_formats* formats, libcamera_pixel_format* pixel_format);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_get_configuration")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_stream_configuration* libcamera_stream_get_configuration(libcamera_stream* stream);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_set_destroy")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void libcamera_stream_set_destroy(libcamera_stream_set* set);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_set_get")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_stream* libcamera_stream_set_get(libcamera_stream_set* set, nuint index);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_stream_set_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial nuint libcamera_stream_set_size(libcamera_stream_set* set);

    // ---- transform.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_orientation_from_rotation")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_orientation libcamera_orientation_from_rotation(int angle, bool* success);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_and")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_transform libcamera_transform_and(libcamera_transform a, libcamera_transform b);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_apply_orientation")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_orientation libcamera_transform_apply_orientation(libcamera_orientation orientation, libcamera_transform transform);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_between_orientations")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_transform libcamera_transform_between_orientations(libcamera_orientation from, libcamera_orientation to);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_combine")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_transform libcamera_transform_combine(libcamera_transform a, libcamera_transform b);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_from_rotation")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_transform libcamera_transform_from_rotation(int angle, [MarshalAs(UnmanagedType.U1)] bool hflip, bool* success);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_hflip")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_transform libcamera_transform_hflip();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_identity")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_transform libcamera_transform_identity();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_inverse")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_transform libcamera_transform_inverse(libcamera_transform transform);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_not")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_transform libcamera_transform_not(libcamera_transform t);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_or")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_transform libcamera_transform_or(libcamera_transform a, libcamera_transform b);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_to_string", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial string? libcamera_transform_to_string(libcamera_transform transform);

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_transpose")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_transform libcamera_transform_transpose();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_vflip")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_transform libcamera_transform_vflip();

    [LibraryImport(LibraryName, EntryPoint = "libcamera_transform_xor")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial libcamera_transform libcamera_transform_xor(libcamera_transform a, libcamera_transform b);

    // ---- version.h ----

    [LibraryImport(LibraryName, EntryPoint = "libcamera_version_string", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    [return: MarshalUsing(typeof(BorrowedUtf8StringMarshaller))] internal static partial string? libcamera_version_string();
}
