// <auto-generated> by src/LibcameraSharp.Core/Generate/gen_pinvoke.py from src/LibcameraSharp.Native/c_api — do not edit. </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace LibcameraSharp.Native.Interop;

#pragma warning disable CS1591, CS8981, IDE1006 // generated: verbatim C names

internal enum libcamera_camera_configuration_status : int
{
    LIBCAMERA_CAMERA_CONFIGURATION_STATUS_VALID = 0,
    LIBCAMERA_CAMERA_CONFIGURATION_STATUS_ADJUSTED = 1,
    LIBCAMERA_CAMERA_CONFIGURATION_STATUS_INVALID = 2,
}

internal enum libcamera_color_space_primaries : int
{
    LIBCAMERA_COLOR_SPACE_PRIMARIES_RAW = 0,
    LIBCAMERA_COLOR_SPACE_PRIMARIES_SMPTE170M = 1,
    LIBCAMERA_COLOR_SPACE_PRIMARIES_REC709 = 2,
    LIBCAMERA_COLOR_SPACE_PRIMARIES_REC2020 = 3,
}

internal enum libcamera_color_space_range : int
{
    LIBCAMERA_COLOR_SPACE_RANGE_FULL = 0,
    LIBCAMERA_COLOR_SPACE_RANGE_LIMITED = 1,
}

internal enum libcamera_color_space_transfer_function : int
{
    LIBCAMERA_COLOR_SPACE_TRANSFER_FUNCTION_LINEAR = 0,
    LIBCAMERA_COLOR_SPACE_TRANSFER_FUNCTION_SRGB = 1,
    LIBCAMERA_COLOR_SPACE_TRANSFER_FUNCTION_REC709 = 2,
}

internal enum libcamera_color_space_ycbcr_encoding : int
{
    LIBCAMERA_COLOR_SPACE_YCBCR_ENCODING_NONE = 0,
    LIBCAMERA_COLOR_SPACE_YCBCR_ENCODING_REC601 = 1,
    LIBCAMERA_COLOR_SPACE_YCBCR_ENCODING_REC709 = 2,
    LIBCAMERA_COLOR_SPACE_YCBCR_ENCODING_REC2020 = 3,
}

internal enum libcamera_control_direction : int
{
    LIBCAMERA_CONTROL_DIRECTION_IN = 1,
    LIBCAMERA_CONTROL_DIRECTION_OUT = 2,
}

internal enum libcamera_control_id_enum : int
{
    libcamera_control_id_DUMMY = 0,
}

internal enum libcamera_control_merge_policy : int
{
    LIBCAMERA_CONTROL_MERGE_KEEP_EXISTING = 0,
    LIBCAMERA_CONTROL_MERGE_OVERWRITE_EXISTING = 1,
}

internal enum libcamera_control_type : int
{
    LIBCAMERA_CONTROL_TYPE_NONE = 0,
    LIBCAMERA_CONTROL_TYPE_BOOL = 1,
    LIBCAMERA_CONTROL_TYPE_BYTE = 2,
    LIBCAMERA_CONTROL_TYPE_UINT16 = 3,
    LIBCAMERA_CONTROL_TYPE_UINT32 = 4,
    LIBCAMERA_CONTROL_TYPE_INT32 = 5,
    LIBCAMERA_CONTROL_TYPE_INT64 = 6,
    LIBCAMERA_CONTROL_TYPE_FLOAT = 7,
    LIBCAMERA_CONTROL_TYPE_STRING = 8,
    LIBCAMERA_CONTROL_TYPE_RECTANGLE = 9,
    LIBCAMERA_CONTROL_TYPE_SIZE = 10,
    LIBCAMERA_CONTROL_TYPE_POINT = 11,
}

internal enum libcamera_frame_metadata_status : int
{
    LIBCAMERA_FRAME_METADATA_STATUS_SUCCESS = 0,
    LIBCAMERA_FRAME_METADATA_STATUS_ERROR = 1,
    LIBCAMERA_FRAME_METADATA_STATUS_CANCELLED = 2,
    LIBCAMERA_FRAME_METADATA_STATUS_STARTUP = 3,
}

internal enum libcamera_logging_stream : int
{
    LIBCAMERA_LOGGING_STREAM_STDOUT = 0,
    LIBCAMERA_LOGGING_STREAM_STDERR = 1,
    LIBCAMERA_LOGGING_STREAM_CUSTOM = 2,
}

internal enum libcamera_logging_target : int
{
    LIBCAMERA_LOGGING_TARGET_NONE = 0,
    LIBCAMERA_LOGGING_TARGET_SYSLOG = 1,
    LIBCAMERA_LOGGING_TARGET_FILE = 2,
    LIBCAMERA_LOGGING_TARGET_STREAM = 3,
}

internal enum libcamera_orientation : int
{
    LIBCAMERA_ORIENTATION_ROTATE_0 = 1,
    LIBCAMERA_ORIENTATION_ROTATE_0_MIRROR = 2,
    LIBCAMERA_ORIENTATION_ROTATE_180 = 3,
    LIBCAMERA_ORIENTATION_ROTATE_180_MIRROR = 4,
    LIBCAMERA_ORIENTATION_ROTATE_90_MIRROR = 5,
    LIBCAMERA_ORIENTATION_ROTATE_270 = 6,
    LIBCAMERA_ORIENTATION_ROTATE_270_MIRROR = 7,
    LIBCAMERA_ORIENTATION_ROTATE_90 = 8,
}

internal enum libcamera_property_id : int
{
    libcamera_property_id_DUMMY = 0,
}

internal enum libcamera_request_reuse_flag : int
{
    LIBCAMERA_REQUEST_REUSE_FLAG_DEFAULT = 0,
    LIBCAMERA_REQUEST_REUSE_FLAG_REUSE_BUFFERS = 1,
}

internal enum libcamera_request_status : int
{
    LIBCAMERA_REQUEST_STATUS_PENDING = 0,
    LIBCAMERA_REQUEST_STATUS_COMPLETE = 1,
    LIBCAMERA_REQUEST_STATUS_CANCELLED = 2,
}

internal enum libcamera_stream_role : int
{
    LIBCAMERA_STREAM_ROLE_RAW = 0,
    LIBCAMERA_STREAM_ROLE_STILL_CAPTURE = 1,
    LIBCAMERA_STREAM_ROLE_VIDEO_RECORDING = 2,
    LIBCAMERA_STREAM_ROLE_VIEW_FINDER = 3,
}

[StructLayout(LayoutKind.Sequential)]
internal struct libcamera_color_space
{
    public libcamera_color_space_primaries primaries;
    public libcamera_color_space_transfer_function transfer_function;
    public libcamera_color_space_ycbcr_encoding ycbcr_encoding;
    public libcamera_color_space_range range;
}

[StructLayout(LayoutKind.Sequential)]
internal struct libcamera_frame_metadata_plane
{
    public uint bytes_used;
}

[StructLayout(LayoutKind.Sequential)]
internal struct libcamera_framebuffer_plane_info
{
    public int fd;
    public uint offset;
    public uint length;
}

[StructLayout(LayoutKind.Sequential)]
internal struct libcamera_pixel_format
{
    public uint fourcc;
    public ulong modifier;
}

[StructLayout(LayoutKind.Sequential)]
internal struct libcamera_point
{
    public int x;
    public int y;
}

[StructLayout(LayoutKind.Sequential)]
internal struct libcamera_rectangle
{
    public int x;
    public int y;
    public uint width;
    public uint height;
}

[StructLayout(LayoutKind.Sequential)]
internal struct libcamera_size
{
    public uint width;
    public uint height;
}

[StructLayout(LayoutKind.Sequential)]
internal struct libcamera_size_range
{
    public libcamera_size min;
    public libcamera_size max;
    public uint hStep;
    public uint vStep;
}

[StructLayout(LayoutKind.Sequential)]
internal struct libcamera_stream_configuration
{
    public libcamera_pixel_format pixel_format;
    public libcamera_size size;
    public uint stride;
    public uint frame_size;
    public uint buffer_count;
}

[StructLayout(LayoutKind.Sequential)]
internal struct libcamera_transform
{
    public uint value;
}

// Opaque handles: only ever used through typed pointers, never instantiated.
internal struct libcamera_callback_handle { }
internal struct libcamera_camera_configuration_t { }
internal struct libcamera_camera_list_t { }
internal struct libcamera_camera_manager_t { }
internal struct libcamera_camera_t { }
internal struct libcamera_control_id { }
internal struct libcamera_control_id_enumerators_iter { }
internal struct libcamera_control_id_map { }
internal struct libcamera_control_id_map_iter { }
internal struct libcamera_control_info { }
internal struct libcamera_control_info_map { }
internal struct libcamera_control_info_map_iter { }
internal struct libcamera_control_list { }
internal struct libcamera_control_list_iter { }
internal struct libcamera_control_value { }
internal struct libcamera_fence { }
internal struct libcamera_frame_metadata { }
internal struct libcamera_frame_metadata_planes { }
internal struct libcamera_framebuffer { }
internal struct libcamera_framebuffer_allocator { }
internal struct libcamera_framebuffer_list { }
internal struct libcamera_framebuffer_plane { }
internal struct libcamera_framebuffer_planes { }
internal struct libcamera_pixel_formats { }
internal struct libcamera_request { }
internal struct libcamera_request_buffer_map { }
internal struct libcamera_request_buffer_map_iter { }
internal struct libcamera_sensor_configuration_t { }
internal struct libcamera_sizes { }
internal struct libcamera_stream { }
internal struct libcamera_stream_formats { }
internal struct libcamera_stream_set { }
