// <auto-generated> by src/LibcameraSharp.Core/Generate/gen_pinvoke.py from src/LibcameraSharp.Native/exif — do not edit. </auto-generated>
#nullable enable

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace LibcameraSharp.Photos.Interop.Exif;

#pragma warning disable CS1591, IDE1006 // generated: verbatim C names

internal static unsafe partial class NativeMethods
{
    internal const string LibraryName = "libexif-shim";
    /// <summary>libcamera headers these bindings were generated against.</summary>
    internal const string GeneratedAgainstLibcamera = "?.?.?";

    // ---- exif_shim.h ----

    /// <summary>
    /// Releases a block from exif_block_new. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "exif_block_free")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void exif_block_free(_ExifData* exif);

    /// <summary>
    /// Releases bytes from exif_block_save. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "exif_block_free_bytes")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void exif_block_free_bytes(byte* bytes);

    /// <summary>
    /// A new, empty EXIF block in little-endian ("Intel") byte order, or NULL. Release with exif_block_free. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "exif_block_new")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial _ExifData* exif_block_new();

    /// <summary>
    /// The block's bytes, starting with "Exif\0\0", or NULL; length receives their count. Release with exif_block_free_bytes. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "exif_block_save")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial byte* exif_block_save(_ExifData* exif, uint* length);

    /// <summary>
    /// Sets tag in directory ifd to size bytes of value, stored as components values of TIFF type format,
    /// replacing any value it had. Returns 0 on success, -1 on failure.
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "exif_block_set")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int exif_block_set(_ExifData* exif, exif_block_ifd ifd, ushort tag, ushort format, uint components, byte* value, uint size);
}
