// <auto-generated> by src/LibcameraSharp.Core/Generate/gen_pinvoke.py from src/LibcameraSharp.Native/exif — do not edit. </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace LibcameraSharp.Photos.Interop.Exif;

#pragma warning disable CS1591, CS8981, IDE1006 // generated: verbatim C names

internal enum exif_block_ifd : int
{
    EXIF_BLOCK_IFD_0 = 0,
    EXIF_BLOCK_IFD_EXIF = 2,
    EXIF_BLOCK_IFD_GPS = 3,
}

// Opaque handles: only ever used through typed pointers, never instantiated.
internal struct _ExifData { }
