#!/usr/bin/env python3
"""Generate typed C# control, property and pixel-format definitions from libcamera's YAML.

Inputs (vendored per libcamera version under src/LibcameraSharp.Core/Generate/inputs/<version>/):
  control_ids_*.yaml, property_ids_*.yaml   every control/property, its type, size, docs, enum values
  control_ranges.yaml                       numeric id base per vendor (libcamera=0, draft=10000, rpi=20000, ...)
  formats.yaml + drm_fourcc.h               pixel format names -> DRM fourcc code + modifier
  log_categories.txt                        every LOG_DEFINE_CATEGORY name in libcamera's source (grep, see CONTRIBUTING)

Outputs (src/LibcameraSharp.Core/Generated/):
  ControlId.g.cs       `enum ControlId`, `enum PropertyId` — numeric ids exactly as libcamera assigns them
  ControlEnums.g.cs    one C# enum per enumerated control (AeState, AfMode, ...)
  Controls.g.cs        `static class Controls` / `Properties` with a typed key per entry, vendors nested
  PixelFormats.g.cs    `static class PixelFormats` with one PixelFormat per libcamera format, plus name lookups
  ControlKeys.g.cs     numeric id -> typed key lookups
  LogCategories.g.cs   `static class LogCategories` with libcamera's log category names

Id assignment mirrors libcamera's gen-controls.py: id = vendor_base + index_in_file + 1.
The YAML descriptions become the xmldoc, since they are written for exactly the reader at the call site.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

HEADER = "// <auto-generated> by src/LibcameraSharp.Core/Generate/gen_controls.py from libcamera's YAML — do not edit. </auto-generated>\n#nullable enable\n"
GENERATED_ATTR = '[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "{version}")]'
NAMESPACE = "LibcameraSharp"

# YAML element type -> (C# managed type, ControlType member name)
TYPE_MAP = {
    "bool": ("bool", "Bool"),
    "uint8_t": ("byte", "Byte"),
    "uint16_t": ("ushort", "Unsigned16"),
    "uint32_t": ("uint", "Unsigned32"),
    "int32_t": ("int", "Integer32"),
    "int64_t": ("long", "Integer64"),
    "float": ("float", "Float"),
    "string": ("string", "String"),
    "Rectangle": ("Rectangle", "Rectangle"),
    "Size": ("Size", "Size"),
    "Point": ("Point", "Point"),
}


@dataclass
class EnumValue:
    name: str
    value: int
    description: str


@dataclass
class Control:
    name: str
    vendor: str
    id: int
    element_type: str
    direction: str            # in | out | inout
    description: str
    size: list | None         # None = scalar, [] entries; a str entry means variable length
    enum_values: list[EnumValue] = field(default_factory=list)

    @property
    def is_array(self) -> bool:
        return self.size is not None

    @property
    def fixed_length(self) -> int | None:
        """Total element count for fixed-size arrays, None when variable or scalar."""
        if not self.is_array or any(isinstance(d, str) for d in self.size):
            return None
        n = 1
        for d in self.size:
            n *= int(d)
        return n

    @property
    def enum_name(self) -> str:
        return self.name

    @property
    def managed_type(self) -> str:
        """C# type used in Control<T>, e.g. `float[]`, `AeState`, `string`."""
        base = self.enum_name if self.enum_values else TYPE_MAP[self.element_type][0]
        return base + "[]" if self.is_array else base


# ---------------------------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------------------------

def load_controls(files: list[Path], ranges: dict[str, int], mode: str) -> list[Control]:
    """Read every control from the given YAML files, assigning ids the way libcamera does."""
    out: list[Control] = []
    for path in files:
        data = yaml.safe_load(path.read_text())
        vendor = data["vendor"]
        if vendor not in ranges:
            raise SystemExit(f"{path.name}: vendor '{vendor}' has no id range in control_ranges.yaml")

        for index, entry in enumerate(data["controls"]):
            (name, spec), = entry.items()
            enum_values = [EnumValue(e["name"], int(e["value"]), (e.get("description") or "").strip())
                           for e in spec.get("enum", [])]
            out.append(Control(
                name=name,
                vendor=vendor,
                id=ranges[vendor] + index + 1,
                element_type=spec["type"],
                direction="out" if mode == "properties" else spec["direction"],
                description=(spec.get("description") or "").strip(),
                size=spec.get("size"),
                enum_values=enum_values,
            ))
    return out


class DrmFourcc:
    """The subset of drm_fourcc.h needed to turn DRM_FORMAT_* / *_MOD_* names into numbers."""

    _code = re.compile(r"#define (DRM_FORMAT_[A-Z0-9_]+)[ \t]+fourcc_code\('(.)', '(.)', '(.)', '(.)'\)")
    _vendor = re.compile(r"#define (DRM_FORMAT_MOD_VENDOR_[A-Z0-9_]+)[ \t]+(0x[0-9a-fA-F]+|[0-9]+)")
    _mod = re.compile(r"#define ([A-Za-z0-9_]+)[ \t]+fourcc_mod_code\(([A-Z0-9_]+), ([0-9a-fA-Fx]+)\)")

    def __init__(self, header: Path) -> None:
        self.codes: dict[str, int] = {}
        self.mods: dict[str, int] = {}
        vendors: dict[str, int] = {}
        for line in header.read_text().splitlines():
            if m := self._code.match(line):
                name, a, b, c, d = m.groups()
                self.codes[name] = ord(a) | ord(b) << 8 | ord(c) << 16 | ord(d) << 24
            elif m := self._vendor.match(line):
                vendors[m.group(1)] = int(m.group(2), 0)
            elif m := self._mod.match(line):
                name, vendor, value = m.groups()
                # fourcc_mod_code(vendor, val) = (vendor << 56) | (val & 0x00ffffffffffffff)
                self.mods[name] = (vendors[f"DRM_FORMAT_MOD_VENDOR_{vendor}"] << 56) | (int(value, 0) & 0x00FFFFFFFFFFFFFF)

    BIG_ENDIAN = 1 << 31


@dataclass
class PixelFormatDef:
    name: str
    fourcc: int
    modifier: int


def load_formats(path: Path, drm: DrmFourcc) -> list[PixelFormatDef]:
    out = []
    for entry in yaml.safe_load(path.read_text())["formats"]:
        (name, spec), = entry.items()
        fourcc = drm.codes[spec["fourcc"]]
        if spec.get("big_endian"):
            fourcc |= DrmFourcc.BIG_ENDIAN
        out.append(PixelFormatDef(name, fourcc, drm.mods[spec["mod"]] if "mod" in spec else 0))
    return out


# ---------------------------------------------------------------------------------------------
# Emitting
# ---------------------------------------------------------------------------------------------

def xml_escape(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def xmldoc(description: str, indent: str) -> list[str]:
    """First paragraph as <summary>, the rest as <remarks>; libcamera's `\\sa X` becomes a see-also line."""
    if not description:
        return []
    text = re.sub(r"\\sa\s+(.+)", r"See also: \1.", description)
    paragraphs = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]
    lines = [f"{indent}/// <summary>"]
    lines += [f"{indent}/// {xml_escape(l)}" for l in paragraphs[0].splitlines()]
    lines.append(f"{indent}/// </summary>")
    if len(paragraphs) > 1:
        lines.append(f"{indent}/// <remarks>")
        for i, p in enumerate(paragraphs[1:]):
            if i:
                lines.append(f"{indent}/// <para/>")
            lines += [f"{indent}/// {xml_escape(l)}" for l in p.splitlines()]
        lines.append(f"{indent}/// </remarks>")
    return lines


def member_names(ctrl: Control) -> dict[str, str]:
    """
    Enum member names without the control's own name repeated in each value: `AeStateIdle` on
    `AeState` becomes `Idle`, `AwbAuto` on `AwbMode` becomes `Auto`, `ExposureLong` on
    `AeExposureMode` becomes `Long`. The longest run of the control name's CamelCase tokens that
    prefixes the value is dropped. Falls back to the full value name when stripping would leave
    an invalid identifier or a duplicate. (C# keywords are lowercase; a remainder always starts
    with a capital, so it can never be one.)
    """
    tokens = re.findall(r"[A-Z][a-z0-9]*|[A-Z]+(?![a-z])", ctrl.name)
    candidates = sorted({"".join(tokens[i:k]) for i in range(len(tokens)) for k in range(i + 1, len(tokens) + 1)}, key=len, reverse=True)

    def strip(name: str) -> str:
        for prefix in candidates:
            rest = name[len(prefix):]
            if name.startswith(prefix) and rest and rest[0].isupper():
                return rest
        return name

    names = {v.name: strip(v.name) for v in ctrl.enum_values}
    if len(set(names.values())) != len(names):
        return {v.name: v.name for v in ctrl.enum_values}   # a collision: keep libcamera's names
    return names


def emit_ids(controls: list[Control], properties: list[Control], version: str) -> str:
    out = [HEADER, f"namespace {NAMESPACE};", ""]
    for enum_name, items, what in (("ControlId", controls, "control"), ("PropertyId", properties, "property")):
        out.append(f"/// <summary>Numeric id of every {what} in libcamera {version}, as libcamera assigns them.</summary>")
        out.append(GENERATED_ATTR.format(version=version))
        out.append(f"public enum {enum_name} : uint")
        out.append("{")
        for c in items:
            summary = c.description.split("\n\n")[0].splitlines()[0] if c.description else ""
            if summary:
                out.append(f"    /// <summary>{xml_escape(summary)}</summary>")
            out.append(f"    {c.name} = {c.id},")
        out.append("}")
        out.append("")
    return "\n".join(out)


def emit_enums(controls: list[Control], version: str) -> str:
    out = [HEADER, f"namespace {NAMESPACE};", ""]
    for c in controls:
        if not c.enum_values:
            continue
        out += xmldoc(c.description, "")
        out.append(GENERATED_ATTR.format(version=version))
        out.append(f"public enum {c.enum_name} : int")
        out.append("{")
        names = member_names(c)
        for v in c.enum_values:
            out += xmldoc(v.description, "    ")
            out.append(f"    {names[v.name]} = {v.value},")
        out.append("}")
        out.append("")
    return "\n".join(out)


def emit_keys(controls: list[Control], properties: list[Control], version: str) -> str:
    out = [HEADER, f"namespace {NAMESPACE};", ""]
    for cls, items, key_type, id_enum, what in (
        ("Controls", controls, "Control", "ControlId", "control"),
        ("Properties", properties, "Property", "PropertyId", "property"),
    ):
        out.append(f"/// <summary>Typed {what} keys. Vendor-specific {what}s live in the nested classes.</summary>")
        out.append(GENERATED_ATTR.format(version=version))
        out.append(f"public static partial class {cls}")
        out.append("{")
        # Core entries directly on the class, each vendor in a nested class named after it.
        by_vendor: dict[str, list[Control]] = {}
        for c in items:
            by_vendor.setdefault(c.vendor, []).append(c)
        for vendor, group in by_vendor.items():
            nested = vendor != "libcamera"
            indent = "        " if nested else "    "
            if nested:
                out.append(f"    /// <summary>{what.capitalize()}s from the '{vendor}' vendor namespace.</summary>")
                out.append("    " + GENERATED_ATTR.format(version=version))
                out.append(f"    public static class {vendor.capitalize()}")
                out.append("    {")
            for c in group:
                out += xmldoc(c.description, indent)
                length = "null" if c.fixed_length is None else str(c.fixed_length)
                ctype = TYPE_MAP[c.element_type][1]
                if key_type == "Control":
                    direction = {"in": "ControlDirection.In", "out": "ControlDirection.Out",
                                 "inout": "ControlDirection.In | ControlDirection.Out"}[c.direction]
                    ctor = f'new({id_enum}.{c.name}, "{c.name}", ControlType.{ctype}, {direction}, isArray: {str(c.is_array).lower()}, fixedLength: {length})'
                else:
                    ctor = f'new({id_enum}.{c.name}, "{c.name}", ControlType.{ctype}, isArray: {str(c.is_array).lower()}, fixedLength: {length})'
                out.append(f"{indent}public static readonly {key_type}<{c.managed_type}> {c.name} = {ctor};")
                out.append("")
            if nested:
                out.append("    }")
                out.append("")
        out.append(f"    /// <summary>Every {what} key above, core and vendor, for lookups by id.</summary>")
        out.append("    public static readonly IReadOnlyList<ControlKey> All =")
        out.append("    [")
        for c in items:
            path = c.name if c.vendor == "libcamera" else f"{c.vendor.capitalize()}.{c.name}"
            out.append(f"        {path},")
        out.append("    ];")
        out.append("}")
        out.append("")
    return "\n".join(out)


def emit_formats(formats: list[PixelFormatDef], version: str) -> str:
    out = [HEADER, f"namespace {NAMESPACE};", ""]
    out.append(f"/// <summary>Every pixel format libcamera {version} defines, by its libcamera name (e.g. <c>RGB888</c>, <c>SRGGB10_CSI2P</c>).</summary>")
    out.append(GENERATED_ATTR.format(version=version))
    out.append("public static partial class PixelFormats")
    out.append("{")
    for f in formats:
        out.append(f'    /// <summary>{f.name}</summary>')
        out.append(f"    public static readonly PixelFormat {f.name} = new(0x{f.fourcc:08X}, 0x{f.modifier:016X});")
    out.append("")
    out.append("    /// <summary>All formats above, for lookups by name or code.</summary>")
    out.append("    public static readonly IReadOnlyList<PixelFormat> All =")
    out.append("    [")
    for f in formats:
        out.append(f"        {f.name},")
    out.append("    ];")
    out.append("")
    out.append("    /// <summary>Every format paired with its libcamera name, in definition order.</summary>")
    out.append("    public static readonly IReadOnlyList<KeyValuePair<string, PixelFormat>> Named =")
    out.append("    [")
    for f in formats:
        out.append(f'        new("{f.name}", {f.name}),')
    out.append("    ];")
    out.append("")
    # Lookups as switches: no static state, so nothing depends on initialisation order or reflection.
    out.append("    /// <summary>libcamera's name for <paramref name=\"format\"/>, or null when it isn't a known format.</summary>")
    out.append("    public static string? NameOf(PixelFormat format) => (format.Fourcc, format.Modifier) switch")
    out.append("    {")
    seen = set()
    for f in formats:
        key = (f.fourcc, f.modifier)
        if key in seen:
            continue                      # first name wins where two names share a code
        seen.add(key)
        out.append(f'        (0x{f.fourcc:08X}, 0x{f.modifier:016X}) => "{f.name}",')
    out.append("        _ => null,")
    out.append("    };")
    out.append("")
    out.append("    /// <summary>The format named <paramref name=\"name\"/>, or null when unknown.</summary>")
    out.append("    public static PixelFormat? ByName(string name) => name switch")
    out.append("    {")
    for f in formats:
        out.append(f'        "{f.name}" => {f.name},')
    out.append("        _ => null,")
    out.append("    };")
    out.append("}")
    out.append("")
    return "\n".join(out)


def emit_key_lookup(controls: list[Control], properties: list[Control], version: str) -> str:
    """ControlKeys: numeric id -> generated key, as switches (no static tables to initialise)."""
    out = [HEADER, f"namespace {NAMESPACE};", ""]
    out.append("/// <summary>Turns libcamera's numeric ids back into the typed keys in <see cref=\"Controls\"/> and <see cref=\"Properties\"/>.</summary>")
    out.append(GENERATED_ATTR.format(version=version))
    out.append("public static class ControlKeys")
    out.append("{")
    for method, items, cls, what in (("ByControlId", controls, "Controls", "control"), ("ByPropertyId", properties, "Properties", "property")):
        out.append(f"    /// <summary>The {what} key with this id, or null when libcamera's id isn't one this binding knows.</summary>")
        out.append(f"    public static ControlKey? {method}(uint id) => id switch")
        out.append("    {")
        for c in items:
            path = f"{cls}.{c.name}" if c.vendor == "libcamera" else f"{cls}.{c.vendor.capitalize()}.{c.name}"
            out.append(f"        {c.id} => {path},")
        out.append("        _ => null,")
        out.append("    };")
        out.append("")
    out.append("}")
    out.append("")
    return "\n".join(out)


def emit_log_categories(names: list[str], version: str) -> str:
    out = [HEADER, f"namespace {NAMESPACE};", ""]
    out.append(f"/// <summary>libcamera {version}'s log categories, for <see cref=\"LibcameraLog.SetLevel(LogLevel, string)\"/>. libcamera matches these exactly; there is no wildcard.</summary>")
    out.append(GENERATED_ATTR.format(version=version))
    out.append("public static class LogCategories")
    out.append("{")
    for n in names:
        out.append(f'    /// <summary><c>{n}</c></summary>')
        out.append(f'    public const string {n} = "{n}";')
    out.append("")
    out.append("    /// <summary>Every category above.</summary>")
    out.append("    public static readonly IReadOnlyList<string> All =")
    out.append("    [")
    for n in names:
        out.append(f"        {n},")
    out.append("    ];")
    out.append("}")
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------------------------

def main() -> int:
    root = Path(__file__).resolve().parents[3]
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--inputs", type=Path, default=None,
                    help="src/LibcameraSharp.Core/Generate/inputs/<version> directory; default: the single directory found there")
    ap.add_argument("--out-dir", type=Path, default=root / "src" / "LibcameraSharp.Core" / "Generated")
    args = ap.parse_args()

    inputs = args.inputs or next(iter(sorted((Path(__file__).resolve().parent / "inputs").iterdir())))
    version = inputs.name.removeprefix("libcamera-")
    ranges = yaml.safe_load((inputs / "control_ranges.yaml").read_text())["ranges"]

    # Same file order as libcamera's meson build, so ids come out identical.
    control_files = [inputs / f"control_ids_{v}.yaml" for v in ("core", "draft", "rpi", "debug") if (inputs / f"control_ids_{v}.yaml").exists()]
    property_files = [inputs / f"property_ids_{v}.yaml" for v in ("core", "draft") if (inputs / f"property_ids_{v}.yaml").exists()]
    controls = load_controls(control_files, ranges, "controls")
    properties = load_controls(property_files, ranges, "properties")
    formats = load_formats(inputs / "formats.yaml", DrmFourcc(inputs / "drm_fourcc.h"))

    # A name clash across vendors would break the flat id enums; fail loudly rather than emit garbage.
    for items, what in ((controls, "controls"), (properties, "properties")):
        names = [c.name for c in items]
        dupes = {n for n in names if names.count(n) > 1}
        if dupes:
            raise SystemExit(f"duplicate {what} names across vendors: {sorted(dupes)}")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "ControlId.g.cs").write_text(emit_ids(controls, properties, version))
    (args.out_dir / "ControlEnums.g.cs").write_text(emit_enums(controls + properties, version))
    (args.out_dir / "Controls.g.cs").write_text(emit_keys(controls, properties, version))
    (args.out_dir / "PixelFormats.g.cs").write_text(emit_formats(formats, version))
    (args.out_dir / "ControlKeys.g.cs").write_text(emit_key_lookup(controls, properties, version))
    categories = (inputs / "log_categories.txt").read_text().split()
    (args.out_dir / "LogCategories.g.cs").write_text(emit_log_categories(categories, version))
    print(f"{len(controls)} controls, {len(properties)} properties, "
          f"{sum(1 for c in controls + properties if c.enum_values)} enums, {len(formats)} pixel formats "
          f"{len(categories)} log categories from libcamera {version} -> {args.out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
