#!/usr/bin/env python3
"""Generate the Bayer format table from libcamera's bayer_format.cpp.

Input (vendored per libcamera version under src/LibcameraSharp.Core/Generate/inputs/<version>/):
  bayer_format.cpp     libcamera's `bayerToFormat` map: (order, bit depth, packing) -> PixelFormat
Output (src/LibcameraSharp.Core/Formats/):
  BayerFormats.g.cs    `static class BayerFormats` with FromPixelFormat / ToPixelFormat switches

libcamera keeps BayerFormat internal (not in the public headers, so not in the shim); its table is
the only source for "what raw layout is this PixelFormat", which the DNG writer and raw unpacking need.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_controls import DrmFourcc, load_formats  # noqa: E402  (the same fourcc table PixelFormats.g.cs is built from)

HEADER = "// <auto-generated> by src/LibcameraSharp.Core/Generate/gen_bayer.py from libcamera's bayer_format.cpp — do not edit. </auto-generated>\n#nullable enable\n"
GENERATED_ATTR = '[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_bayer.py", "{version}")]'

ENTRY = re.compile(
    r"\{\s*\{\s*BayerFormat::(?P<order>\w+),\s*(?P<bits>\d+),\s*BayerFormat::Packing::(?P<packing>\w+)\s*\},\s*"
    r"\{\s*formats::(?P<format>\w+),", re.S)

PACKING = {"None": "None", "CSI2": "Csi2", "IPU3": "Ipu3", "PISP1": "Pisp1", "PISP2": "Pisp2"}
ORDER = {"BGGR": "BGGR", "GBRG": "GBRG", "GRBG": "GRBG", "RGGB": "RGGB", "MONO": "Mono"}


def emit(entries: list[tuple[str, int, str, str]], codes: dict[str, tuple[int, int]], version: str) -> str:
    out = [HEADER, "namespace LibcameraSharp.Core;", ""]
    out.append(f"/// <summary>libcamera {version}'s table of raw (Bayer and mono) pixel formats and their layout: colour order, bit depth, packing.</summary>")
    out.append(GENERATED_ATTR.format(version=version))
    out.append("public static class BayerFormats")
    out.append("{")
    out.append("    /// <summary>The layout of a raw <paramref name=\"format\"/>, or null when it isn't a raw format libcamera knows.</summary>")
    out.append("    public static BayerFormat? FromPixelFormat(PixelFormat format) => (format.Fourcc, format.Modifier) switch")
    out.append("    {")
    for order, bits, packing, fmt in entries:
        fourcc, modifier = codes[fmt]
        out.append(f"        (0x{fourcc:08X}, 0x{modifier:016X}) => new(BayerOrder.{order}, {bits}, BayerPacking.{packing}),   // {fmt}")
    out.append("        _ => null,")
    out.append("    };")
    out.append("")
    out.append("    /// <summary>The pixel format for a raw layout, or null when libcamera has none for it.</summary>")
    out.append("    public static PixelFormat? ToPixelFormat(BayerFormat bayer) => (bayer.Order, bayer.BitDepth, bayer.Packing) switch")
    out.append("    {")
    for order, bits, packing, fmt in entries:
        out.append(f"        (BayerOrder.{order}, {bits}, BayerPacking.{packing}) => PixelFormats.{fmt},")
    out.append("        _ => null,")
    out.append("    };")
    out.append("}")
    return "\n".join(out) + "\n"


def main() -> int:
    root = Path(__file__).resolve().parents[3]
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--inputs", type=Path, default=None)
    ap.add_argument("--out-dir", type=Path, default=root / "src" / "LibcameraSharp.Core" / "Formats")
    args = ap.parse_args()
    inputs = args.inputs or next(iter(sorted((Path(__file__).resolve().parent / "inputs").iterdir())))
    version = inputs.name.removeprefix("libcamera-")

    source = (inputs / "bayer_format.cpp").read_text()
    table = source[source.index("bayerToFormat{"):]
    table = table[:table.index("\n};")]
    entries = [(ORDER[m["order"]], int(m["bits"]), PACKING[m["packing"]], m["format"]) for m in ENTRY.finditer(table)]
    if not entries:
        raise SystemExit("no entries parsed from bayerToFormat")
    codes = {f.name: (f.fourcc, f.modifier) for f in load_formats(inputs / "formats.yaml", DrmFourcc(inputs / "drm_fourcc.h"))}
    missing = sorted({fmt for *_, fmt in entries} - codes.keys())
    if missing:
        raise SystemExit(f"bayer_format.cpp names formats missing from formats.yaml: {missing}")
    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "BayerFormats.g.cs").write_text(emit(entries, codes, version))
    print(f"{len(entries)} Bayer formats from libcamera {version} -> {args.out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
