// <auto-generated> by src/LibcameraSharp.Core/Generate/gen_pinvoke.py from src/LibcameraSharp.Native/tiff — do not edit. </auto-generated>
#nullable enable

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace LibcameraSharp.Photos.Interop.Tiff;

#pragma warning disable CS1591, IDE1006 // generated: verbatim C names

internal static unsafe partial class NativeMethods
{
    internal const string LibraryName = "libtiff-shim";
    /// <summary>libcamera headers these bindings were generated against.</summary>
    internal const string GeneratedAgainstLibcamera = "?.?.?";

    // ---- tiff_shim.h ----

    /// <summary>
    /// Writes the current directory so far, keeping it current (TIFFCheckpointDirectory). Returns 1 on success. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_checkpoint_directory")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_checkpoint_directory(tiff* tif);

    /// <summary>
    /// Flushes and closes the file (TIFFClose). */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_close")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial void tiff_close(tiff* tif);

    /// <summary>
    /// Starts an EXIF directory (TIFFCreateEXIFDirectory). Returns 0 on success. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_create_exif_directory")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_create_exif_directory(tiff* tif);

    /// <summary>
    /// The current directory's offset in the file (TIFFCurrentDirOffset). */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_current_directory_offset")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial ulong tiff_current_directory_offset(tiff* tif);

    /// <summary>
    /// libtiff's description of a tag in the current directory (TIFFFieldWithTag), or NULL if unknown. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_field")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial _TIFFField* tiff_field(tiff* tif, uint tag);

    /// <summary>
    /// Bytes of the count TIFFSetField reads first: 2 or 4, else 0 (TIFFFieldSetGetCountSize). */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_field_count_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_field_count_size(_TIFFField* field);

    /// <summary>
    /// The tag's TIFFDataType (TIFFFieldDataType). */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_field_data_type")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_field_data_type(_TIFFField* field);

    /// <summary>
    /// Non-zero when TIFFSetField expects a count before the values (TIFFFieldPassCount). */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_field_passes_count")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_field_passes_count(_TIFFField* field);

    /// <summary>
    /// How many values the tag holds, or a negative marker for variable (TIFFFieldReadCount). */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_field_read_count")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_field_read_count(_TIFFField* field);

    /// <summary>
    /// Bytes per value as TIFFSetField reads it (TIFFFieldSetGetSize). */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_field_value_size")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_field_value_size(_TIFFField* field);

    /// <summary>
    /// Opens a TIFF file (TIFFOpen); mode "w" creates it. Returns NULL on failure. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_open", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial tiff* tiff_open(string path, string mode);

    /// <summary>
    /// Registers the CFARepeatPatternDim and CFAPattern tags when this libtiff lacks them: libtiff 4.5.1 lost
    /// them from its field table. Returns 0 when they were already known or are now registered.
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_register_cfa_fields")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_register_cfa_fields(tiff* tif);

    /// <summary>
    /// Makes directory index (from 0) current again (TIFFSetDirectory). Returns 1 on success. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_set_directory")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_set_directory(tiff* tif, uint index);

    /// <summary>
    /// TIFFSetField for C0 tags: an array whose length the tag fixes, such as TIFFTAG_DNGVERSION. Returns 1 on success. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_set_field_array")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_set_field_array(tiff* tif, uint tag, void* values);

    /// <summary>
    /// TIFFSetField for C16 and C32 tags: a count, then the array. Returns 1 on success. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_set_field_counted_array")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_set_field_counted_array(tiff* tif, uint tag, int count, void* values);

    /// <summary>
    /// TIFFSetField for FLOAT and DOUBLE tags: a float is read as a promoted double. Returns 1 on success. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_set_field_double")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_set_field_double(tiff* tif, uint tag, double value);

    /// <summary>
    /// TIFFSetField for ASCII tags. Returns 1 on success. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_set_field_string", StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_set_field_string(tiff* tif, uint tag, string value);

    /// <summary>
    /// TIFFSetField for UINT16 and UINT32 tags: a 16-bit value is read as a promoted int. Returns 1 on success. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_set_field_uint32")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_set_field_uint32(tiff* tif, uint tag, uint value);

    /// <summary>
    /// TIFFSetField for IFD8 tags, such as TIFFTAG_EXIFIFD. Returns 1 on success. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_set_field_uint64")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_set_field_uint64(tiff* tif, uint tag, ulong value);

    /// <summary>
    /// Removes directory number (from 1) from the chain (TIFFUnlinkDirectory). Returns 1 on success. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_unlink_directory")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_unlink_directory(tiff* tif, uint number);

    /// <summary>
    /// Writes the current directory and starts a new one (TIFFWriteDirectory). Returns 1 on success. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_write_directory")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_write_directory(tiff* tif);

    /// <summary>
    /// Writes one row of the current directory's image (TIFFWriteScanline, sample 0). Returns 1 on success. */
    /// </summary>
    [LibraryImport(LibraryName, EntryPoint = "tiff_write_scanline")]
    [UnmanagedCallConv(CallConvs = [typeof(System.Runtime.CompilerServices.CallConvCdecl)])]
    internal static partial int tiff_write_scanline(tiff* tif, void* row, uint index);
}
