// <auto-generated> by src/LibcameraSharp.Core/Generate/gen_pinvoke.py from src/LibcameraSharp.Native/tiff — do not edit. </auto-generated>
#nullable enable

using System.Runtime.InteropServices;

namespace LibcameraSharp.Photos.Interop.Tiff;

#pragma warning disable CS1591, CS8981, IDE1006 // generated: verbatim C names

// Opaque handles: only ever used through typed pointers, never instantiated.
internal struct _TIFFField { }
internal struct tiff { }
