// <auto-generated> by src/LibcameraSharp.Core/Generate/gen_controls.py from libcamera's YAML — do not edit. </auto-generated>
#nullable enable

namespace LibcameraSharp;

/// <summary>Every pixel format libcamera 0.7.2+rpt20260817 defines, by its libcamera name (e.g. <c>RGB888</c>, <c>SRGGB10_CSI2P</c>).</summary>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public static partial class PixelFormats
{
    /// <summary>R8</summary>
    public static readonly PixelFormat R8 = new(0x20203852, 0x0000000000000000);
    /// <summary>R10</summary>
    public static readonly PixelFormat R10 = new(0x20303152, 0x0000000000000000);
    /// <summary>R12</summary>
    public static readonly PixelFormat R12 = new(0x20323152, 0x0000000000000000);
    /// <summary>R16</summary>
    public static readonly PixelFormat R16 = new(0x20363152, 0x0000000000000000);
    /// <summary>RGB565</summary>
    public static readonly PixelFormat RGB565 = new(0x36314752, 0x0000000000000000);
    /// <summary>RGB565_BE</summary>
    public static readonly PixelFormat RGB565_BE = new(0xB6314752, 0x0000000000000000);
    /// <summary>RGB888</summary>
    public static readonly PixelFormat RGB888 = new(0x34324752, 0x0000000000000000);
    /// <summary>BGR888</summary>
    public static readonly PixelFormat BGR888 = new(0x34324742, 0x0000000000000000);
    /// <summary>XRGB8888</summary>
    public static readonly PixelFormat XRGB8888 = new(0x34325258, 0x0000000000000000);
    /// <summary>XBGR8888</summary>
    public static readonly PixelFormat XBGR8888 = new(0x34324258, 0x0000000000000000);
    /// <summary>RGBX8888</summary>
    public static readonly PixelFormat RGBX8888 = new(0x34325852, 0x0000000000000000);
    /// <summary>BGRX8888</summary>
    public static readonly PixelFormat BGRX8888 = new(0x34325842, 0x0000000000000000);
    /// <summary>ARGB8888</summary>
    public static readonly PixelFormat ARGB8888 = new(0x34325241, 0x0000000000000000);
    /// <summary>ABGR8888</summary>
    public static readonly PixelFormat ABGR8888 = new(0x34324241, 0x0000000000000000);
    /// <summary>RGBA8888</summary>
    public static readonly PixelFormat RGBA8888 = new(0x34324152, 0x0000000000000000);
    /// <summary>BGRA8888</summary>
    public static readonly PixelFormat BGRA8888 = new(0x34324142, 0x0000000000000000);
    /// <summary>RGB161616</summary>
    public static readonly PixelFormat RGB161616 = new(0x38344752, 0x0000000000000000);
    /// <summary>BGR161616</summary>
    public static readonly PixelFormat BGR161616 = new(0x38344742, 0x0000000000000000);
    /// <summary>YUYV</summary>
    public static readonly PixelFormat YUYV = new(0x56595559, 0x0000000000000000);
    /// <summary>YVYU</summary>
    public static readonly PixelFormat YVYU = new(0x55595659, 0x0000000000000000);
    /// <summary>UYVY</summary>
    public static readonly PixelFormat UYVY = new(0x59565955, 0x0000000000000000);
    /// <summary>VYUY</summary>
    public static readonly PixelFormat VYUY = new(0x59555956, 0x0000000000000000);
    /// <summary>AVUY8888</summary>
    public static readonly PixelFormat AVUY8888 = new(0x59555641, 0x0000000000000000);
    /// <summary>XVUY8888</summary>
    public static readonly PixelFormat XVUY8888 = new(0x59555658, 0x0000000000000000);
    /// <summary>NV12</summary>
    public static readonly PixelFormat NV12 = new(0x3231564E, 0x0000000000000000);
    /// <summary>NV21</summary>
    public static readonly PixelFormat NV21 = new(0x3132564E, 0x0000000000000000);
    /// <summary>NV16</summary>
    public static readonly PixelFormat NV16 = new(0x3631564E, 0x0000000000000000);
    /// <summary>NV61</summary>
    public static readonly PixelFormat NV61 = new(0x3136564E, 0x0000000000000000);
    /// <summary>NV24</summary>
    public static readonly PixelFormat NV24 = new(0x3432564E, 0x0000000000000000);
    /// <summary>NV42</summary>
    public static readonly PixelFormat NV42 = new(0x3234564E, 0x0000000000000000);
    /// <summary>YUV420</summary>
    public static readonly PixelFormat YUV420 = new(0x32315559, 0x0000000000000000);
    /// <summary>YVU420</summary>
    public static readonly PixelFormat YVU420 = new(0x32315659, 0x0000000000000000);
    /// <summary>YUV422</summary>
    public static readonly PixelFormat YUV422 = new(0x36315559, 0x0000000000000000);
    /// <summary>YVU422</summary>
    public static readonly PixelFormat YVU422 = new(0x36315659, 0x0000000000000000);
    /// <summary>YUV444</summary>
    public static readonly PixelFormat YUV444 = new(0x34325559, 0x0000000000000000);
    /// <summary>YVU444</summary>
    public static readonly PixelFormat YVU444 = new(0x34325659, 0x0000000000000000);
    /// <summary>MJPEG</summary>
    public static readonly PixelFormat MJPEG = new(0x47504A4D, 0x0000000000000000);
    /// <summary>SRGGB8</summary>
    public static readonly PixelFormat SRGGB8 = new(0x42474752, 0x0000000000000000);
    /// <summary>SGRBG8</summary>
    public static readonly PixelFormat SGRBG8 = new(0x47425247, 0x0000000000000000);
    /// <summary>SGBRG8</summary>
    public static readonly PixelFormat SGBRG8 = new(0x47524247, 0x0000000000000000);
    /// <summary>SBGGR8</summary>
    public static readonly PixelFormat SBGGR8 = new(0x31384142, 0x0000000000000000);
    /// <summary>SRGGB10</summary>
    public static readonly PixelFormat SRGGB10 = new(0x30314752, 0x0000000000000000);
    /// <summary>SGRBG10</summary>
    public static readonly PixelFormat SGRBG10 = new(0x30314142, 0x0000000000000000);
    /// <summary>SGBRG10</summary>
    public static readonly PixelFormat SGBRG10 = new(0x30314247, 0x0000000000000000);
    /// <summary>SBGGR10</summary>
    public static readonly PixelFormat SBGGR10 = new(0x30314742, 0x0000000000000000);
    /// <summary>SRGGB12</summary>
    public static readonly PixelFormat SRGGB12 = new(0x32314752, 0x0000000000000000);
    /// <summary>SGRBG12</summary>
    public static readonly PixelFormat SGRBG12 = new(0x32314142, 0x0000000000000000);
    /// <summary>SGBRG12</summary>
    public static readonly PixelFormat SGBRG12 = new(0x32314247, 0x0000000000000000);
    /// <summary>SBGGR12</summary>
    public static readonly PixelFormat SBGGR12 = new(0x32314742, 0x0000000000000000);
    /// <summary>SRGGB14</summary>
    public static readonly PixelFormat SRGGB14 = new(0x34314752, 0x0000000000000000);
    /// <summary>SGRBG14</summary>
    public static readonly PixelFormat SGRBG14 = new(0x34314142, 0x0000000000000000);
    /// <summary>SGBRG14</summary>
    public static readonly PixelFormat SGBRG14 = new(0x34314247, 0x0000000000000000);
    /// <summary>SBGGR14</summary>
    public static readonly PixelFormat SBGGR14 = new(0x34314742, 0x0000000000000000);
    /// <summary>SRGGB16</summary>
    public static readonly PixelFormat SRGGB16 = new(0x36424752, 0x0000000000000000);
    /// <summary>SGRBG16</summary>
    public static readonly PixelFormat SGRBG16 = new(0x36315247, 0x0000000000000000);
    /// <summary>SGBRG16</summary>
    public static readonly PixelFormat SGBRG16 = new(0x36314247, 0x0000000000000000);
    /// <summary>SBGGR16</summary>
    public static readonly PixelFormat SBGGR16 = new(0x32525942, 0x0000000000000000);
    /// <summary>R10_CSI2P</summary>
    public static readonly PixelFormat R10_CSI2P = new(0x20303152, 0x0B00000000000001);
    /// <summary>R12_CSI2P</summary>
    public static readonly PixelFormat R12_CSI2P = new(0x20323152, 0x0B00000000000001);
    /// <summary>SRGGB10_CSI2P</summary>
    public static readonly PixelFormat SRGGB10_CSI2P = new(0x30314752, 0x0B00000000000001);
    /// <summary>SGRBG10_CSI2P</summary>
    public static readonly PixelFormat SGRBG10_CSI2P = new(0x30314142, 0x0B00000000000001);
    /// <summary>SGBRG10_CSI2P</summary>
    public static readonly PixelFormat SGBRG10_CSI2P = new(0x30314247, 0x0B00000000000001);
    /// <summary>SBGGR10_CSI2P</summary>
    public static readonly PixelFormat SBGGR10_CSI2P = new(0x30314742, 0x0B00000000000001);
    /// <summary>SRGGB12_CSI2P</summary>
    public static readonly PixelFormat SRGGB12_CSI2P = new(0x32314752, 0x0B00000000000001);
    /// <summary>SGRBG12_CSI2P</summary>
    public static readonly PixelFormat SGRBG12_CSI2P = new(0x32314142, 0x0B00000000000001);
    /// <summary>SGBRG12_CSI2P</summary>
    public static readonly PixelFormat SGBRG12_CSI2P = new(0x32314247, 0x0B00000000000001);
    /// <summary>SBGGR12_CSI2P</summary>
    public static readonly PixelFormat SBGGR12_CSI2P = new(0x32314742, 0x0B00000000000001);
    /// <summary>SRGGB14_CSI2P</summary>
    public static readonly PixelFormat SRGGB14_CSI2P = new(0x34314752, 0x0B00000000000001);
    /// <summary>SGRBG14_CSI2P</summary>
    public static readonly PixelFormat SGRBG14_CSI2P = new(0x34314142, 0x0B00000000000001);
    /// <summary>SGBRG14_CSI2P</summary>
    public static readonly PixelFormat SGBRG14_CSI2P = new(0x34314247, 0x0B00000000000001);
    /// <summary>SBGGR14_CSI2P</summary>
    public static readonly PixelFormat SBGGR14_CSI2P = new(0x34314742, 0x0B00000000000001);
    /// <summary>SRGGB10_IPU3</summary>
    public static readonly PixelFormat SRGGB10_IPU3 = new(0x30314752, 0x010000000000000D);
    /// <summary>SGRBG10_IPU3</summary>
    public static readonly PixelFormat SGRBG10_IPU3 = new(0x30314142, 0x010000000000000D);
    /// <summary>SGBRG10_IPU3</summary>
    public static readonly PixelFormat SGBRG10_IPU3 = new(0x30314247, 0x010000000000000D);
    /// <summary>SBGGR10_IPU3</summary>
    public static readonly PixelFormat SBGGR10_IPU3 = new(0x30314742, 0x010000000000000D);
    /// <summary>RGGB_PISP_COMP1</summary>
    public static readonly PixelFormat RGGB_PISP_COMP1 = new(0x36424752, 0x0C00000000000001);
    /// <summary>GRBG_PISP_COMP1</summary>
    public static readonly PixelFormat GRBG_PISP_COMP1 = new(0x36315247, 0x0C00000000000001);
    /// <summary>GBRG_PISP_COMP1</summary>
    public static readonly PixelFormat GBRG_PISP_COMP1 = new(0x36314247, 0x0C00000000000001);
    /// <summary>BGGR_PISP_COMP1</summary>
    public static readonly PixelFormat BGGR_PISP_COMP1 = new(0x32525942, 0x0C00000000000001);
    /// <summary>MONO_PISP_COMP1</summary>
    public static readonly PixelFormat MONO_PISP_COMP1 = new(0x20363152, 0x0C00000000000001);

    /// <summary>All formats above, for lookups by name or code.</summary>
    public static readonly IReadOnlyList<PixelFormat> All =
    [
        R8,
        R10,
        R12,
        R16,
        RGB565,
        RGB565_BE,
        RGB888,
        BGR888,
        XRGB8888,
        XBGR8888,
        RGBX8888,
        BGRX8888,
        ARGB8888,
        ABGR8888,
        RGBA8888,
        BGRA8888,
        RGB161616,
        BGR161616,
        YUYV,
        YVYU,
        UYVY,
        VYUY,
        AVUY8888,
        XVUY8888,
        NV12,
        NV21,
        NV16,
        NV61,
        NV24,
        NV42,
        YUV420,
        YVU420,
        YUV422,
        YVU422,
        YUV444,
        YVU444,
        MJPEG,
        SRGGB8,
        SGRBG8,
        SGBRG8,
        SBGGR8,
        SRGGB10,
        SGRBG10,
        SGBRG10,
        SBGGR10,
        SRGGB12,
        SGRBG12,
        SGBRG12,
        SBGGR12,
        SRGGB14,
        SGRBG14,
        SGBRG14,
        SBGGR14,
        SRGGB16,
        SGRBG16,
        SGBRG16,
        SBGGR16,
        R10_CSI2P,
        R12_CSI2P,
        SRGGB10_CSI2P,
        SGRBG10_CSI2P,
        SGBRG10_CSI2P,
        SBGGR10_CSI2P,
        SRGGB12_CSI2P,
        SGRBG12_CSI2P,
        SGBRG12_CSI2P,
        SBGGR12_CSI2P,
        SRGGB14_CSI2P,
        SGRBG14_CSI2P,
        SGBRG14_CSI2P,
        SBGGR14_CSI2P,
        SRGGB10_IPU3,
        SGRBG10_IPU3,
        SGBRG10_IPU3,
        SBGGR10_IPU3,
        RGGB_PISP_COMP1,
        GRBG_PISP_COMP1,
        GBRG_PISP_COMP1,
        BGGR_PISP_COMP1,
        MONO_PISP_COMP1,
    ];

    /// <summary>Every format paired with its libcamera name, in definition order.</summary>
    public static readonly IReadOnlyList<KeyValuePair<string, PixelFormat>> Named =
    [
        new("R8", R8),
        new("R10", R10),
        new("R12", R12),
        new("R16", R16),
        new("RGB565", RGB565),
        new("RGB565_BE", RGB565_BE),
        new("RGB888", RGB888),
        new("BGR888", BGR888),
        new("XRGB8888", XRGB8888),
        new("XBGR8888", XBGR8888),
        new("RGBX8888", RGBX8888),
        new("BGRX8888", BGRX8888),
        new("ARGB8888", ARGB8888),
        new("ABGR8888", ABGR8888),
        new("RGBA8888", RGBA8888),
        new("BGRA8888", BGRA8888),
        new("RGB161616", RGB161616),
        new("BGR161616", BGR161616),
        new("YUYV", YUYV),
        new("YVYU", YVYU),
        new("UYVY", UYVY),
        new("VYUY", VYUY),
        new("AVUY8888", AVUY8888),
        new("XVUY8888", XVUY8888),
        new("NV12", NV12),
        new("NV21", NV21),
        new("NV16", NV16),
        new("NV61", NV61),
        new("NV24", NV24),
        new("NV42", NV42),
        new("YUV420", YUV420),
        new("YVU420", YVU420),
        new("YUV422", YUV422),
        new("YVU422", YVU422),
        new("YUV444", YUV444),
        new("YVU444", YVU444),
        new("MJPEG", MJPEG),
        new("SRGGB8", SRGGB8),
        new("SGRBG8", SGRBG8),
        new("SGBRG8", SGBRG8),
        new("SBGGR8", SBGGR8),
        new("SRGGB10", SRGGB10),
        new("SGRBG10", SGRBG10),
        new("SGBRG10", SGBRG10),
        new("SBGGR10", SBGGR10),
        new("SRGGB12", SRGGB12),
        new("SGRBG12", SGRBG12),
        new("SGBRG12", SGBRG12),
        new("SBGGR12", SBGGR12),
        new("SRGGB14", SRGGB14),
        new("SGRBG14", SGRBG14),
        new("SGBRG14", SGBRG14),
        new("SBGGR14", SBGGR14),
        new("SRGGB16", SRGGB16),
        new("SGRBG16", SGRBG16),
        new("SGBRG16", SGBRG16),
        new("SBGGR16", SBGGR16),
        new("R10_CSI2P", R10_CSI2P),
        new("R12_CSI2P", R12_CSI2P),
        new("SRGGB10_CSI2P", SRGGB10_CSI2P),
        new("SGRBG10_CSI2P", SGRBG10_CSI2P),
        new("SGBRG10_CSI2P", SGBRG10_CSI2P),
        new("SBGGR10_CSI2P", SBGGR10_CSI2P),
        new("SRGGB12_CSI2P", SRGGB12_CSI2P),
        new("SGRBG12_CSI2P", SGRBG12_CSI2P),
        new("SGBRG12_CSI2P", SGBRG12_CSI2P),
        new("SBGGR12_CSI2P", SBGGR12_CSI2P),
        new("SRGGB14_CSI2P", SRGGB14_CSI2P),
        new("SGRBG14_CSI2P", SGRBG14_CSI2P),
        new("SGBRG14_CSI2P", SGBRG14_CSI2P),
        new("SBGGR14_CSI2P", SBGGR14_CSI2P),
        new("SRGGB10_IPU3", SRGGB10_IPU3),
        new("SGRBG10_IPU3", SGRBG10_IPU3),
        new("SGBRG10_IPU3", SGBRG10_IPU3),
        new("SBGGR10_IPU3", SBGGR10_IPU3),
        new("RGGB_PISP_COMP1", RGGB_PISP_COMP1),
        new("GRBG_PISP_COMP1", GRBG_PISP_COMP1),
        new("GBRG_PISP_COMP1", GBRG_PISP_COMP1),
        new("BGGR_PISP_COMP1", BGGR_PISP_COMP1),
        new("MONO_PISP_COMP1", MONO_PISP_COMP1),
    ];

    /// <summary>libcamera's name for <paramref name="format"/>, or null when it isn't a known format.</summary>
    public static string? NameOf(PixelFormat format) => (format.Fourcc, format.Modifier) switch
    {
        (0x20203852, 0x0000000000000000) => "R8",
        (0x20303152, 0x0000000000000000) => "R10",
        (0x20323152, 0x0000000000000000) => "R12",
        (0x20363152, 0x0000000000000000) => "R16",
        (0x36314752, 0x0000000000000000) => "RGB565",
        (0xB6314752, 0x0000000000000000) => "RGB565_BE",
        (0x34324752, 0x0000000000000000) => "RGB888",
        (0x34324742, 0x0000000000000000) => "BGR888",
        (0x34325258, 0x0000000000000000) => "XRGB8888",
        (0x34324258, 0x0000000000000000) => "XBGR8888",
        (0x34325852, 0x0000000000000000) => "RGBX8888",
        (0x34325842, 0x0000000000000000) => "BGRX8888",
        (0x34325241, 0x0000000000000000) => "ARGB8888",
        (0x34324241, 0x0000000000000000) => "ABGR8888",
        (0x34324152, 0x0000000000000000) => "RGBA8888",
        (0x34324142, 0x0000000000000000) => "BGRA8888",
        (0x38344752, 0x0000000000000000) => "RGB161616",
        (0x38344742, 0x0000000000000000) => "BGR161616",
        (0x56595559, 0x0000000000000000) => "YUYV",
        (0x55595659, 0x0000000000000000) => "YVYU",
        (0x59565955, 0x0000000000000000) => "UYVY",
        (0x59555956, 0x0000000000000000) => "VYUY",
        (0x59555641, 0x0000000000000000) => "AVUY8888",
        (0x59555658, 0x0000000000000000) => "XVUY8888",
        (0x3231564E, 0x0000000000000000) => "NV12",
        (0x3132564E, 0x0000000000000000) => "NV21",
        (0x3631564E, 0x0000000000000000) => "NV16",
        (0x3136564E, 0x0000000000000000) => "NV61",
        (0x3432564E, 0x0000000000000000) => "NV24",
        (0x3234564E, 0x0000000000000000) => "NV42",
        (0x32315559, 0x0000000000000000) => "YUV420",
        (0x32315659, 0x0000000000000000) => "YVU420",
        (0x36315559, 0x0000000000000000) => "YUV422",
        (0x36315659, 0x0000000000000000) => "YVU422",
        (0x34325559, 0x0000000000000000) => "YUV444",
        (0x34325659, 0x0000000000000000) => "YVU444",
        (0x47504A4D, 0x0000000000000000) => "MJPEG",
        (0x42474752, 0x0000000000000000) => "SRGGB8",
        (0x47425247, 0x0000000000000000) => "SGRBG8",
        (0x47524247, 0x0000000000000000) => "SGBRG8",
        (0x31384142, 0x0000000000000000) => "SBGGR8",
        (0x30314752, 0x0000000000000000) => "SRGGB10",
        (0x30314142, 0x0000000000000000) => "SGRBG10",
        (0x30314247, 0x0000000000000000) => "SGBRG10",
        (0x30314742, 0x0000000000000000) => "SBGGR10",
        (0x32314752, 0x0000000000000000) => "SRGGB12",
        (0x32314142, 0x0000000000000000) => "SGRBG12",
        (0x32314247, 0x0000000000000000) => "SGBRG12",
        (0x32314742, 0x0000000000000000) => "SBGGR12",
        (0x34314752, 0x0000000000000000) => "SRGGB14",
        (0x34314142, 0x0000000000000000) => "SGRBG14",
        (0x34314247, 0x0000000000000000) => "SGBRG14",
        (0x34314742, 0x0000000000000000) => "SBGGR14",
        (0x36424752, 0x0000000000000000) => "SRGGB16",
        (0x36315247, 0x0000000000000000) => "SGRBG16",
        (0x36314247, 0x0000000000000000) => "SGBRG16",
        (0x32525942, 0x0000000000000000) => "SBGGR16",
        (0x20303152, 0x0B00000000000001) => "R10_CSI2P",
        (0x20323152, 0x0B00000000000001) => "R12_CSI2P",
        (0x30314752, 0x0B00000000000001) => "SRGGB10_CSI2P",
        (0x30314142, 0x0B00000000000001) => "SGRBG10_CSI2P",
        (0x30314247, 0x0B00000000000001) => "SGBRG10_CSI2P",
        (0x30314742, 0x0B00000000000001) => "SBGGR10_CSI2P",
        (0x32314752, 0x0B00000000000001) => "SRGGB12_CSI2P",
        (0x32314142, 0x0B00000000000001) => "SGRBG12_CSI2P",
        (0x32314247, 0x0B00000000000001) => "SGBRG12_CSI2P",
        (0x32314742, 0x0B00000000000001) => "SBGGR12_CSI2P",
        (0x34314752, 0x0B00000000000001) => "SRGGB14_CSI2P",
        (0x34314142, 0x0B00000000000001) => "SGRBG14_CSI2P",
        (0x34314247, 0x0B00000000000001) => "SGBRG14_CSI2P",
        (0x34314742, 0x0B00000000000001) => "SBGGR14_CSI2P",
        (0x30314752, 0x010000000000000D) => "SRGGB10_IPU3",
        (0x30314142, 0x010000000000000D) => "SGRBG10_IPU3",
        (0x30314247, 0x010000000000000D) => "SGBRG10_IPU3",
        (0x30314742, 0x010000000000000D) => "SBGGR10_IPU3",
        (0x36424752, 0x0C00000000000001) => "RGGB_PISP_COMP1",
        (0x36315247, 0x0C00000000000001) => "GRBG_PISP_COMP1",
        (0x36314247, 0x0C00000000000001) => "GBRG_PISP_COMP1",
        (0x32525942, 0x0C00000000000001) => "BGGR_PISP_COMP1",
        (0x20363152, 0x0C00000000000001) => "MONO_PISP_COMP1",
        _ => null,
    };

    /// <summary>The format named <paramref name="name"/>, or null when unknown.</summary>
    public static PixelFormat? ByName(string name) => name switch
    {
        "R8" => R8,
        "R10" => R10,
        "R12" => R12,
        "R16" => R16,
        "RGB565" => RGB565,
        "RGB565_BE" => RGB565_BE,
        "RGB888" => RGB888,
        "BGR888" => BGR888,
        "XRGB8888" => XRGB8888,
        "XBGR8888" => XBGR8888,
        "RGBX8888" => RGBX8888,
        "BGRX8888" => BGRX8888,
        "ARGB8888" => ARGB8888,
        "ABGR8888" => ABGR8888,
        "RGBA8888" => RGBA8888,
        "BGRA8888" => BGRA8888,
        "RGB161616" => RGB161616,
        "BGR161616" => BGR161616,
        "YUYV" => YUYV,
        "YVYU" => YVYU,
        "UYVY" => UYVY,
        "VYUY" => VYUY,
        "AVUY8888" => AVUY8888,
        "XVUY8888" => XVUY8888,
        "NV12" => NV12,
        "NV21" => NV21,
        "NV16" => NV16,
        "NV61" => NV61,
        "NV24" => NV24,
        "NV42" => NV42,
        "YUV420" => YUV420,
        "YVU420" => YVU420,
        "YUV422" => YUV422,
        "YVU422" => YVU422,
        "YUV444" => YUV444,
        "YVU444" => YVU444,
        "MJPEG" => MJPEG,
        "SRGGB8" => SRGGB8,
        "SGRBG8" => SGRBG8,
        "SGBRG8" => SGBRG8,
        "SBGGR8" => SBGGR8,
        "SRGGB10" => SRGGB10,
        "SGRBG10" => SGRBG10,
        "SGBRG10" => SGBRG10,
        "SBGGR10" => SBGGR10,
        "SRGGB12" => SRGGB12,
        "SGRBG12" => SGRBG12,
        "SGBRG12" => SGBRG12,
        "SBGGR12" => SBGGR12,
        "SRGGB14" => SRGGB14,
        "SGRBG14" => SGRBG14,
        "SGBRG14" => SGBRG14,
        "SBGGR14" => SBGGR14,
        "SRGGB16" => SRGGB16,
        "SGRBG16" => SGRBG16,
        "SGBRG16" => SGBRG16,
        "SBGGR16" => SBGGR16,
        "R10_CSI2P" => R10_CSI2P,
        "R12_CSI2P" => R12_CSI2P,
        "SRGGB10_CSI2P" => SRGGB10_CSI2P,
        "SGRBG10_CSI2P" => SGRBG10_CSI2P,
        "SGBRG10_CSI2P" => SGBRG10_CSI2P,
        "SBGGR10_CSI2P" => SBGGR10_CSI2P,
        "SRGGB12_CSI2P" => SRGGB12_CSI2P,
        "SGRBG12_CSI2P" => SGRBG12_CSI2P,
        "SGBRG12_CSI2P" => SGBRG12_CSI2P,
        "SBGGR12_CSI2P" => SBGGR12_CSI2P,
        "SRGGB14_CSI2P" => SRGGB14_CSI2P,
        "SGRBG14_CSI2P" => SGRBG14_CSI2P,
        "SGBRG14_CSI2P" => SGBRG14_CSI2P,
        "SBGGR14_CSI2P" => SBGGR14_CSI2P,
        "SRGGB10_IPU3" => SRGGB10_IPU3,
        "SGRBG10_IPU3" => SGRBG10_IPU3,
        "SGBRG10_IPU3" => SGBRG10_IPU3,
        "SBGGR10_IPU3" => SBGGR10_IPU3,
        "RGGB_PISP_COMP1" => RGGB_PISP_COMP1,
        "GRBG_PISP_COMP1" => GRBG_PISP_COMP1,
        "GBRG_PISP_COMP1" => GBRG_PISP_COMP1,
        "BGGR_PISP_COMP1" => BGGR_PISP_COMP1,
        "MONO_PISP_COMP1" => MONO_PISP_COMP1,
        _ => null,
    };
}
