// <auto-generated> by src/LibcameraSharp.Core/Generate/gen_controls.py from libcamera's YAML — do not edit. </auto-generated>
#nullable enable

namespace LibcameraSharp;

/// <summary>
/// Report the AEGC algorithm state.
/// </summary>
/// <remarks>
/// The AEGC algorithm computes the exposure time and the analogue gain
/// to be applied to the image sensor.
/// <para/>
/// The AEGC algorithm behaviour is controlled by the ExposureTimeMode and
/// AnalogueGainMode controls, which allow applications to decide how
/// the exposure time and gain are computed, in Auto or Manual mode,
/// independently from one another.
/// <para/>
/// The AeState control reports the AEGC algorithm state through a single
/// value and describes it as a single computation block which computes
/// both the exposure time and the analogue gain values.
/// <para/>
/// When both the exposure time and analogue gain values are configured to
/// be in Manual mode, the AEGC algorithm is quiescent and does not actively
/// compute any value and the AeState control will report AeStateIdle.
/// <para/>
/// When at least the exposure time or analogue gain are configured to be
/// computed by the AEGC algorithm, the AeState control will report if the
/// algorithm has converged to stable values for all of the controls set
/// to be computed in Auto mode.
/// <para/>
/// See also: AnalogueGainMode.
/// See also: ExposureTimeMode.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AeState : int
{
    /// <summary>
    /// The AEGC algorithm is inactive.
    /// </summary>
    /// <remarks>
    /// This state is returned when both AnalogueGainMode and
    /// ExposureTimeMode are set to Manual and the algorithm is not
    /// actively computing any value.
    /// </remarks>
    Idle = 0,
    /// <summary>
    /// The AEGC algorithm is actively computing new values, for either the
    /// exposure time or the analogue gain, but has not converged to a
    /// stable result yet.
    /// </summary>
    /// <remarks>
    /// This state is returned if at least one of AnalogueGainMode or
    /// ExposureTimeMode is auto and the algorithm hasn't converged yet.
    /// <para/>
    /// The AEGC algorithm converges once stable values are computed for
    /// all of the controls set to be computed in Auto mode. Once the
    /// algorithm converges the state is moved to AeStateConverged.
    /// </remarks>
    Searching = 1,
    /// <summary>
    /// The AEGC algorithm has converged.
    /// </summary>
    /// <remarks>
    /// This state is returned if at least one of AnalogueGainMode or
    /// ExposureTimeMode is Auto, and the AEGC algorithm has converged to a
    /// stable value.
    /// <para/>
    /// If the measurements move too far away from the convergence point
    /// then the AEGC algorithm might start adjusting again, in which case
    /// the state is moved to AeStateSearching.
    /// </remarks>
    Converged = 2,
}

/// <summary>
/// Specify a metering mode for the AE algorithm to use.
/// </summary>
/// <remarks>
/// The metering modes determine which parts of the image are used to
/// determine the scene brightness. Metering modes may be platform specific
/// and not all metering modes may be supported.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AeMeteringMode : int
{
    /// <summary>
    /// Centre-weighted metering mode.
    /// </summary>
    CentreWeighted = 0,
    /// <summary>
    /// Spot metering mode.
    /// </summary>
    Spot = 1,
    /// <summary>
    /// Matrix metering mode.
    /// </summary>
    Matrix = 2,
    /// <summary>
    /// Custom metering mode.
    /// </summary>
    Custom = 3,
}

/// <summary>
/// Specify a constraint mode for the AE algorithm to use.
/// </summary>
/// <remarks>
/// The constraint modes determine how the measured scene brightness is
/// adjusted to reach the desired target exposure. Constraint modes may be
/// platform specific, and not all constraint modes may be supported.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AeConstraintMode : int
{
    /// <summary>
    /// Default constraint mode.
    /// </summary>
    /// <remarks>
    /// This mode aims to balance the exposure of different parts of the
    /// image so as to reach a reasonable average level. However, highlights
    /// in the image may appear over-exposed and lowlights may appear
    /// under-exposed.
    /// </remarks>
    Normal = 0,
    /// <summary>
    /// Highlight constraint mode.
    /// </summary>
    /// <remarks>
    /// This mode adjusts the exposure levels in order to try and avoid
    /// over-exposing the brightest parts (highlights) of an image.
    /// Other non-highlight parts of the image may appear under-exposed.
    /// </remarks>
    Highlight = 1,
    /// <summary>
    /// Shadows constraint mode.
    /// </summary>
    /// <remarks>
    /// This mode adjusts the exposure levels in order to try and avoid
    /// under-exposing the dark parts (shadows) of an image. Other normally
    /// exposed parts of the image may appear over-exposed.
    /// </remarks>
    Shadows = 2,
    /// <summary>
    /// Custom constraint mode.
    /// </summary>
    Custom = 3,
}

/// <summary>
/// Specify an exposure mode for the AE algorithm to use.
/// </summary>
/// <remarks>
/// The exposure modes specify how the desired total exposure is divided
/// between the exposure time and the sensor's analogue gain. They are
/// platform specific, and not all exposure modes may be supported.
/// <para/>
/// When one of AnalogueGainMode or ExposureTimeMode is set to Manual,
/// the fixed values will override any choices made by AeExposureMode.
/// <para/>
/// See also: AnalogueGainMode.
/// See also: ExposureTimeMode.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AeExposureMode : int
{
    /// <summary>
    /// Default exposure mode.
    /// </summary>
    Normal = 0,
    /// <summary>
    /// Exposure mode allowing only short exposure times.
    /// </summary>
    Short = 1,
    /// <summary>
    /// Exposure mode allowing long exposure times.
    /// </summary>
    Long = 2,
    /// <summary>
    /// Custom exposure mode.
    /// </summary>
    Custom = 3,
}

/// <summary>
/// Controls the source of the exposure time that is applied to the image
/// sensor.
/// </summary>
/// <remarks>
/// When set to Auto, the AE algorithm computes the exposure time and
/// configures the image sensor accordingly. When set to Manual, the value
/// of the ExposureTime control is used.
/// <para/>
/// When transitioning from Auto to Manual mode and no ExposureTime control
/// is provided by the application, the last value computed by the AE
/// algorithm when the mode was Auto will be used. If the ExposureTimeMode
/// was never set to Auto (either because the camera started in Manual mode,
/// or Auto is not supported by the camera), the camera should use a
/// best-effort default value.
/// <para/>
/// If ExposureTimeModeManual is supported, the ExposureTime control must
/// also be supported.
/// <para/>
/// Cameras that support manual control of the sensor shall support manual
/// mode for both ExposureTimeMode and AnalogueGainMode, and shall expose
/// the ExposureTime and AnalogueGain controls. If the camera also has an
/// AEGC implementation, both ExposureTimeMode and AnalogueGainMode shall
/// support both manual and auto mode. If auto mode is available, it shall
/// be the default mode. These rules do not apply to black box cameras
/// such as UVC cameras, where the available gain and exposure modes are
/// completely dependent on what the device exposes.
/// <para/>
/// \par Flickerless exposure mode transitions
/// <para/>
/// Applications that wish to transition from ExposureTimeModeAuto to direct
/// control of the exposure time without causing extra flicker can do so by
/// selecting an ExposureTime value as close as possible to the last value
/// computed by the auto exposure algorithm in order to avoid any visible
/// flickering.
/// <para/>
/// To select the correct value to use as ExposureTime value, applications
/// should accommodate the natural delay in applying controls caused by the
/// capture pipeline frame depth.
/// <para/>
/// When switching to manual exposure mode, applications should not
/// immediately specify an ExposureTime value in the same request where
/// ExposureTimeMode is set to Manual. They should instead wait for the
/// first Request where ExposureTimeMode is reported as
/// ExposureTimeModeManual in the Request metadata, and use the reported
/// ExposureTime to populate the control value in the next Request to be
/// queued to the Camera.
/// <para/>
/// The implementation of the auto-exposure algorithm should equally try to
/// minimize flickering and when transitioning from manual exposure mode to
/// auto exposure use the last value provided by the application as starting
/// point.
/// <para/>
/// 1. Start with ExposureTimeMode set to Auto
/// <para/>
/// 2. Set ExposureTimeMode to Manual
/// <para/>
/// 3. Wait for the first completed request that has ExposureTimeMode
/// set to Manual
/// <para/>
/// 4. Copy the value reported in ExposureTime into a new request, and
/// submit it
/// <para/>
/// 5. Proceed to run manual exposure time as desired
/// <para/>
/// See also: ExposureTime.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum ExposureTimeMode : int
{
    /// <summary>
    /// The exposure time will be calculated automatically and set by the
    /// AE algorithm.
    /// </summary>
    /// <remarks>
    /// If ExposureTime is set while this mode is active, it will be
    /// ignored, and its value will not be retained.
    /// <para/>
    /// When transitioning from Manual to Auto mode, the AEGC should start
    /// its adjustments based on the last set manual ExposureTime value.
    /// </remarks>
    Auto = 0,
    /// <summary>
    /// The exposure time will not be updated by the AE algorithm.
    /// </summary>
    /// <remarks>
    /// When transitioning from Auto to Manual mode, the last computed
    /// exposure value is used until a new value is specified through the
    /// ExposureTime control. If an ExposureTime value is specified in the
    /// same request where the ExposureTimeMode is changed from Auto to
    /// Manual, the provided ExposureTime is applied immediately.
    /// </remarks>
    Manual = 1,
}

/// <summary>
/// Controls the source of the analogue gain that is applied to the image
/// sensor.
/// </summary>
/// <remarks>
/// When set to Auto, the AEGC algorithm computes the analogue gain and
/// configures the image sensor accordingly. When set to Manual, the value
/// of the AnalogueGain control is used.
/// <para/>
/// When transitioning from Auto to Manual mode and no AnalogueGain control
/// is provided by the application, the last value computed by the AEGC
/// algorithm when the mode was Auto will be used. If the AnalogueGainMode
/// was never set to Auto (either because the camera started in Manual mode,
/// or Auto is not supported by the camera), the camera should use a
/// best-effort default value.
/// <para/>
/// If AnalogueGainModeManual is supported, the AnalogueGain control must
/// also be supported.
/// <para/>
/// For cameras where we have control over the ISP, both ExposureTimeMode
/// and AnalogueGainMode are expected to support manual mode, and both
/// controls (as well as ExposureTimeMode and AnalogueGain) are expected to
/// be present. If the camera also has an AEGC implementation, both
/// ExposureTimeMode and AnalogueGainMode shall support both manual and
/// auto mode. If auto mode is available, it shall be the default mode.
/// These rules do not apply to black box cameras such as UVC cameras,
/// where the available gain and exposure modes are completely dependent on
/// what the hardware exposes.
/// <para/>
/// The same procedure described for performing flickerless transitions in
/// the ExposureTimeMode control documentation can be applied to analogue
/// gain.
/// <para/>
/// See also: ExposureTimeMode.
/// See also: AnalogueGain.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AnalogueGainMode : int
{
    /// <summary>
    /// The analogue gain will be calculated automatically and set by the
    /// AEGC algorithm.
    /// </summary>
    /// <remarks>
    /// If AnalogueGain is set while this mode is active, it will be
    /// ignored, and it will also not be retained.
    /// <para/>
    /// When transitioning from Manual to Auto mode, the AEGC should start
    /// its adjustments based on the last set manual AnalogueGain value.
    /// </remarks>
    Auto = 0,
    /// <summary>
    /// The analogue gain will not be updated by the AEGC algorithm.
    /// </summary>
    /// <remarks>
    /// When transitioning from Auto to Manual mode, the last computed
    /// gain value is used until a new value is specified through the
    /// AnalogueGain control. If an AnalogueGain value is specified in the
    /// same request where the AnalogueGainMode is changed from Auto to
    /// Manual, the provided AnalogueGain is applied immediately.
    /// </remarks>
    Manual = 1,
}

/// <summary>
/// Set the flicker avoidance mode for AGC/AEC.
/// </summary>
/// <remarks>
/// The flicker mode determines whether, and how, the AGC/AEC algorithm
/// attempts to hide flicker effects caused by the duty cycle of artificial
/// lighting.
/// <para/>
/// Although implementation dependent, many algorithms for "flicker
/// avoidance" work by restricting this exposure time to integer multiples
/// of the cycle period, wherever possible.
/// <para/>
/// Implementations may not support all of the flicker modes listed below.
/// <para/>
/// By default the system will start in FlickerAuto mode if this is
/// supported, otherwise the flicker mode will be set to FlickerOff.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AeFlickerMode : int
{
    /// <summary>
    /// No flicker avoidance is performed.
    /// </summary>
    Off = 0,
    /// <summary>
    /// Manual flicker avoidance.
    /// </summary>
    /// <remarks>
    /// Suppress flicker effects caused by lighting running with a period
    /// specified by the AeFlickerPeriod control.
    /// See also: AeFlickerPeriod.
    /// </remarks>
    Manual = 1,
    /// <summary>
    /// Automatic flicker period detection and avoidance.
    /// </summary>
    /// <remarks>
    /// The system will automatically determine the most likely value of
    /// flicker period, and avoid flicker of this frequency. Once flicker
    /// is being corrected, it is implementation dependent whether the
    /// system is still able to detect a change in the flicker period.
    /// See also: AeFlickerDetected.
    /// </remarks>
    Auto = 2,
}

/// <summary>
/// Specify the range of illuminants to use for the AWB algorithm.
/// </summary>
/// <remarks>
/// The modes supported are platform specific, and not all modes may be
/// supported.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AwbMode : int
{
    /// <summary>
    /// Search over the whole colour temperature range.
    /// </summary>
    Auto = 0,
    /// <summary>
    /// Incandescent AWB lamp mode.
    /// </summary>
    Incandescent = 1,
    /// <summary>
    /// Tungsten AWB lamp mode.
    /// </summary>
    Tungsten = 2,
    /// <summary>
    /// Fluorescent AWB lamp mode.
    /// </summary>
    Fluorescent = 3,
    /// <summary>
    /// Indoor AWB lighting mode.
    /// </summary>
    Indoor = 4,
    /// <summary>
    /// Daylight AWB lighting mode.
    /// </summary>
    Daylight = 5,
    /// <summary>
    /// Cloudy AWB lighting mode.
    /// </summary>
    Cloudy = 6,
    /// <summary>
    /// Custom AWB mode.
    /// </summary>
    Custom = 7,
}

/// <summary>
/// The mode of the AF (autofocus) algorithm.
/// </summary>
/// <remarks>
/// An implementation may choose not to implement all the modes.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AfMode : int
{
    /// <summary>
    /// The AF algorithm is in manual mode.
    /// </summary>
    /// <remarks>
    /// In this mode it will never perform any action nor move the lens of
    /// its own accord, but an application can specify the desired lens
    /// position using the LensPosition control. The AfState will always
    /// report AfStateIdle.
    /// <para/>
    /// If the camera is started in AfModeManual, it will move the focus
    /// lens to the position specified by the LensPosition control.
    /// <para/>
    /// This mode is the recommended default value for the AfMode control.
    /// External cameras (as reported by the Location property set to
    /// CameraLocationExternal) may use a different default value.
    /// </remarks>
    Manual = 0,
    /// <summary>
    /// The AF algorithm is in auto mode.
    /// </summary>
    /// <remarks>
    /// In this mode the algorithm will never move the lens or change state
    /// unless the AfTrigger control is used. The AfTrigger control can be
    /// used to initiate a focus scan, the results of which will be
    /// reported by AfState.
    /// <para/>
    /// If the autofocus algorithm is moved from AfModeAuto to another mode
    /// while a scan is in progress, the scan is cancelled immediately,
    /// without waiting for the scan to finish.
    /// <para/>
    /// When first entering this mode the AfState will report AfStateIdle.
    /// When a trigger control is sent, AfState will report AfStateScanning
    /// for a period before spontaneously changing to AfStateFocused or
    /// AfStateFailed, depending on the outcome of the scan. It will remain
    /// in this state until another scan is initiated by the AfTrigger
    /// control. If a scan is cancelled (without changing to another mode),
    /// AfState will return to AfStateIdle.
    /// </remarks>
    Auto = 1,
    /// <summary>
    /// The AF algorithm is in continuous mode.
    /// </summary>
    /// <remarks>
    /// In this mode the lens can re-start a scan spontaneously at any
    /// moment, without any user intervention. The AfState still reports
    /// whether the algorithm is currently scanning or not, though the
    /// application has no ability to initiate or cancel scans, nor to move
    /// the lens for itself.
    /// <para/>
    /// However, applications can pause the AF algorithm from continuously
    /// scanning by using the AfPause control. This allows video or still
    /// images to be captured whilst guaranteeing that the focus is fixed.
    /// <para/>
    /// When set to AfModeContinuous, the system will immediately initiate a
    /// scan so AfState will report AfStateScanning, and will settle on one
    /// of AfStateFocused or AfStateFailed, depending on the scan result.
    /// </remarks>
    Continuous = 2,
}

/// <summary>
/// The range of focus distances that is scanned.
/// </summary>
/// <remarks>
/// An implementation may choose not to implement all the options here.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AfRange : int
{
    /// <summary>
    /// A wide range of focus distances is scanned.
    /// </summary>
    /// <remarks>
    /// Scanned distances cover all the way from infinity down to close
    /// distances, though depending on the implementation, possibly not
    /// including the very closest macro positions.
    /// </remarks>
    Normal = 0,
    /// <summary>
    /// Only close distances are scanned.
    /// </summary>
    Macro = 1,
    /// <summary>
    /// The full range of focus distances is scanned.
    /// </summary>
    /// <remarks>
    /// This range is similar to AfRangeNormal but includes the very
    /// closest macro positions.
    /// </remarks>
    Full = 2,
}

/// <summary>
/// Determine whether the AF is to move the lens as quickly as possible or
/// more steadily.
/// </summary>
/// <remarks>
/// For example, during video recording it may be desirable not to move the
/// lens too abruptly, but when in a preview mode (waiting for a still
/// capture) it may be helpful to move the lens as quickly as is reasonably
/// possible.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AfSpeed : int
{
    /// <summary>
    /// Move the lens at its usual speed.
    /// </summary>
    Normal = 0,
    /// <summary>
    /// Move the lens more quickly.
    /// </summary>
    Fast = 1,
}

/// <summary>
/// The parts of the image used by the AF algorithm to measure focus.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AfMetering : int
{
    /// <summary>
    /// Let the AF algorithm decide for itself where it will measure focus.
    /// </summary>
    Auto = 0,
    /// <summary>
    /// Use the rectangles defined by the AfWindows control to measure focus.
    /// </summary>
    /// <remarks>
    /// If no windows are specified the behaviour is platform dependent.
    /// </remarks>
    Windows = 1,
}

/// <summary>
/// Start an autofocus scan.
/// </summary>
/// <remarks>
/// This control starts an autofocus scan when AfMode is set to AfModeAuto,
/// and is ignored if AfMode is set to AfModeManual or AfModeContinuous. It
/// can also be used to terminate a scan early.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AfTrigger : int
{
    /// <summary>
    /// Start an AF scan.
    /// </summary>
    /// <remarks>
    /// Setting the control to AfTriggerStart is ignored if a scan is in
    /// progress.
    /// </remarks>
    Start = 0,
    /// <summary>
    /// Cancel an AF scan.
    /// </summary>
    /// <remarks>
    /// This does not cause the lens to move anywhere else. Ignored if no
    /// scan is in progress.
    /// </remarks>
    Cancel = 1,
}

/// <summary>
/// Pause lens movements when in continuous autofocus mode.
/// </summary>
/// <remarks>
/// This control has no effect except when in continuous autofocus mode
/// (AfModeContinuous). It can be used to pause any lens movements while
/// (for example) images are captured. The algorithm remains inactive
/// until it is instructed to resume.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AfPause : int
{
    /// <summary>
    /// Pause the continuous autofocus algorithm immediately.
    /// </summary>
    /// <remarks>
    /// The autofocus algorithm is paused whether or not any kind of scan
    /// is underway. AfPauseState will subsequently report
    /// AfPauseStatePaused. AfState may report any of AfStateScanning,
    /// AfStateFocused or AfStateFailed, depending on the algorithm's state
    /// when it received this control.
    /// </remarks>
    Immediate = 0,
    /// <summary>
    /// Pause the continuous autofocus algorithm at the end of the scan.
    /// </summary>
    /// <remarks>
    /// This is similar to AfPauseImmediate, and if the AfState is
    /// currently reporting AfStateFocused or AfStateFailed it will remain
    /// in that state and AfPauseState will report AfPauseStatePaused.
    /// <para/>
    /// However, if the algorithm is scanning (AfStateScanning),
    /// AfPauseState will report AfPauseStatePausing until the scan is
    /// finished, at which point AfState will report one of AfStateFocused
    /// or AfStateFailed, and AfPauseState will change to
    /// AfPauseStatePaused.
    /// </remarks>
    Deferred = 1,
    /// <summary>
    /// Resume continuous autofocus operation.
    /// </summary>
    /// <remarks>
    /// The algorithm starts again from exactly where it left off, and
    /// AfPauseState will report AfPauseStateRunning.
    /// </remarks>
    Resume = 2,
}

/// <summary>
/// The current state of the AF algorithm.
/// </summary>
/// <remarks>
/// This control reports the current state of the AF algorithm in
/// conjunction with the reported AfMode value and (in continuous AF mode)
/// the AfPauseState value. The possible state changes are described below,
/// though we note the following state transitions that occur when the
/// AfMode is changed.
/// <para/>
/// If the AfMode is set to AfModeManual, then the AfState will always
/// report AfStateIdle (even if the lens is subsequently moved). Changing
/// to the AfModeManual state does not initiate any lens movement.
/// <para/>
/// If the AfMode is set to AfModeAuto then the AfState will report
/// AfStateIdle. However, if AfModeAuto and AfTriggerStart are sent
/// together then AfState will omit AfStateIdle and move straight to
/// AfStateScanning (and start a scan).
/// <para/>
/// If the AfMode is set to AfModeContinuous then the AfState will
/// initially report AfStateScanning.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AfState : int
{
    /// <summary>
    /// The AF algorithm is in manual mode (AfModeManual) or in auto mode
    /// (AfModeAuto) and a scan has not yet been triggered, or an
    /// in-progress scan was cancelled.
    /// </summary>
    Idle = 0,
    /// <summary>
    /// The AF algorithm is in auto mode (AfModeAuto), and a scan has been
    /// started using the AfTrigger control.
    /// </summary>
    /// <remarks>
    /// The scan can be cancelled by sending AfTriggerCancel at which point
    /// the algorithm will either move back to AfStateIdle or, if the scan
    /// actually completes before the cancel request is processed, to one
    /// of AfStateFocused or AfStateFailed.
    /// <para/>
    /// Alternatively the AF algorithm could be in continuous mode
    /// (AfModeContinuous) at which point it may enter this state
    /// spontaneously whenever it determines that a rescan is needed.
    /// </remarks>
    Scanning = 1,
    /// <summary>
    /// The AF algorithm is in auto (AfModeAuto) or continuous
    /// (AfModeContinuous) mode and a scan has completed with the result
    /// that the algorithm believes the image is now in focus.
    /// </summary>
    Focused = 2,
    /// <summary>
    /// The AF algorithm is in auto (AfModeAuto) or continuous
    /// (AfModeContinuous) mode and a scan has completed with the result
    /// that the algorithm did not find a good focus position.
    /// </summary>
    Failed = 3,
}

/// <summary>
/// Report whether the autofocus is currently running, paused or pausing.
/// </summary>
/// <remarks>
/// This control is only applicable in continuous (AfModeContinuous) mode,
/// and reports whether the algorithm is currently running, paused or
/// pausing (that is, will pause as soon as any in-progress scan
/// completes).
/// <para/>
/// Any change to AfMode will cause AfPauseStateRunning to be reported.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AfPauseState : int
{
    /// <summary>
    /// Continuous AF is running and the algorithm may restart a scan
    /// spontaneously.
    /// </summary>
    Running = 0,
    /// <summary>
    /// Continuous AF has been sent an AfPauseDeferred control, and will
    /// pause as soon as any in-progress scan completes.
    /// </summary>
    /// <remarks>
    /// When the scan completes, the AfPauseState control will report
    /// AfPauseStatePaused. No new scans will be start spontaneously until
    /// the AfPauseResume control is sent.
    /// </remarks>
    Pausing = 1,
    /// <summary>
    /// Continuous AF is paused.
    /// </summary>
    /// <remarks>
    /// No further state changes or lens movements will occur until the
    /// AfPauseResume control is sent.
    /// </remarks>
    Paused = 2,
}

/// <summary>
/// Set the mode to be used for High Dynamic Range (HDR) imaging.
/// </summary>
/// <remarks>
/// HDR techniques typically include multiple exposure, image fusion and
/// tone mapping techniques to improve the dynamic range of the resulting
/// images.
/// <para/>
/// When using an HDR mode, images are captured with different sets of AGC
/// settings called HDR channels. Channels indicate in particular the type
/// of exposure (short, medium or long) used to capture the raw image,
/// before fusion. Each HDR image is tagged with the corresponding channel
/// using the HdrChannel control.
/// <para/>
/// See also: HdrChannel.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum HdrMode : int
{
    /// <summary>
    /// HDR is disabled.
    /// </summary>
    /// <remarks>
    /// Metadata for this frame will not include the HdrChannel control.
    /// </remarks>
    Off = 0,
    /// <summary>
    /// Multiple exposures will be generated in an alternating fashion.
    /// </summary>
    /// <remarks>
    /// The multiple exposures will not be merged together and will be
    /// returned to the application as they are. Each image will be tagged
    /// with the correct HDR channel, indicating what kind of exposure it
    /// is. The tag should be the same as in the HdrModeMultiExposure case.
    /// <para/>
    /// The expectation is that an application using this mode would merge
    /// the frames to create HDR images for itself if it requires them.
    /// </remarks>
    MultiExposureUnmerged = 1,
    /// <summary>
    /// Multiple exposures will be generated and merged to create HDR
    /// images.
    /// </summary>
    /// <remarks>
    /// Each image will be tagged with the HDR channel (long, medium or
    /// short) that arrived and which caused this image to be output.
    /// <para/>
    /// Systems that use two channels for HDR will return images tagged
    /// alternately as the short and long channel. Systems that use three
    /// channels for HDR will cycle through the short, medium and long
    /// channel before repeating.
    /// </remarks>
    MultiExposure = 2,
    /// <summary>
    /// Multiple frames all at a single exposure will be used to create HDR
    /// images.
    /// </summary>
    /// <remarks>
    /// These images should be reported as all corresponding to the HDR
    /// short channel.
    /// </remarks>
    SingleExposure = 3,
    /// <summary>
    /// Multiple frames will be combined to produce "night mode" images.
    /// </summary>
    /// <remarks>
    /// It is up to the implementation exactly which HDR channels it uses,
    /// and the images will all be tagged accordingly with the correct HDR
    /// channel information.
    /// </remarks>
    Night = 4,
}

/// <summary>
/// The HDR channel used to capture the frame.
/// </summary>
/// <remarks>
/// This value is reported back to the application so that it can discover
/// whether this capture corresponds to the short or long exposure image
/// (or any other image used by the HDR procedure). An application can
/// monitor the HDR channel to discover when the differently exposed images
/// have arrived.
/// <para/>
/// This metadata is only available when an HDR mode has been enabled.
/// <para/>
/// See also: HdrMode.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum HdrChannel : int
{
    /// <summary>
    /// This image does not correspond to any of the captures used to create
    /// an HDR image.
    /// </summary>
    None = 0,
    /// <summary>
    /// This is a short exposure image.
    /// </summary>
    Short = 1,
    /// <summary>
    /// This is a medium exposure image.
    /// </summary>
    Medium = 2,
    /// <summary>
    /// This is a long exposure image.
    /// </summary>
    Long = 3,
}

/// <summary>
/// Set the WDR mode.
/// </summary>
/// <remarks>
/// The WDR mode is used to select the algorithm used for global tone
/// mapping. It will automatically reduce the exposure time of the sensor
/// so that there are only a small number of saturated pixels in the image.
/// The algorithm then compensates for the loss of brightness by applying a
/// global tone mapping curve to the image.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum WdrMode : int
{
    /// <summary>
    /// Wdr is disabled.
    /// </summary>
    Off = 0,
    /// <summary>
    /// Apply a linear global tone mapping curve.
    /// A curve with two linear sections is applied. This produces good results at the expense of a slightly artificial look.
    /// </summary>
    Linear = 1,
    /// <summary>
    /// Apply a power global tone mapping curve.
    /// </summary>
    /// <remarks>
    /// This curve has high gain values on the dark areas of an image and
    /// high compression values on the bright area. It therefore tends to
    /// produce noticeable noise artifacts.
    /// </remarks>
    Power = 2,
    /// <summary>
    /// Apply an exponential global tone mapping curve.
    /// </summary>
    /// <remarks>
    /// This curve has lower gain values in dark areas compared to the power
    /// curve but produces a more natural look compared to the linear curve.
    /// It is therefore the best choice for most scenes.
    /// </remarks>
    Exponential = 3,
    /// <summary>
    /// Apply histogram equalization.
    /// </summary>
    /// <remarks>
    /// This curve preserves most of the information of the image at the
    /// expense of a very artificial look. It is therefore best suited for
    /// technical analysis.
    /// </remarks>
    HistogramEqualization = 4,
}

/// <summary>
/// Control for AE metering trigger. Currently identical to
/// ANDROID_CONTROL_AE_PRECAPTURE_TRIGGER.
/// </summary>
/// <remarks>
/// Whether the camera device will trigger a precapture metering sequence
/// when it processes this request.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AePrecaptureTrigger : int
{
    /// <summary>
    /// The trigger is idle.
    /// </summary>
    Idle = 0,
    /// <summary>
    /// The pre-capture AE metering is started by the camera.
    /// </summary>
    Start = 1,
    /// <summary>
    /// The camera will cancel any active or completed metering sequence.
    /// The AE algorithm is reset to its initial state.
    /// </summary>
    Cancel = 2,
}

/// <summary>
/// Control to select the noise reduction algorithm mode. Currently
/// identical to ANDROID_NOISE_REDUCTION_MODE.
/// </summary>
/// <remarks>
/// Mode of operation for the noise reduction algorithm.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum NoiseReductionMode : int
{
    /// <summary>
    /// No noise reduction is applied
    /// </summary>
    Off = 0,
    /// <summary>
    /// Noise reduction is applied without reducing the frame rate.
    /// </summary>
    Fast = 1,
    /// <summary>
    /// High quality noise reduction at the expense of frame rate.
    /// </summary>
    HighQuality = 2,
    /// <summary>
    /// Minimal noise reduction is applied without reducing the frame rate.
    /// </summary>
    Minimal = 3,
    /// <summary>
    /// Noise reduction is applied at different levels to different streams.
    /// </summary>
    ZSL = 4,
}

/// <summary>
/// Control to select the color correction aberration mode. Currently
/// identical to ANDROID_COLOR_CORRECTION_ABERRATION_MODE.
/// </summary>
/// <remarks>
/// Mode of operation for the chromatic aberration correction algorithm.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum ColorCorrectionAberrationMode : int
{
    /// <summary>
    /// No aberration correction is applied.
    /// </summary>
    Off = 0,
    /// <summary>
    /// Aberration correction will not slow down the frame rate.
    /// </summary>
    Fast = 1,
    /// <summary>
    /// High quality aberration correction which might reduce the frame
    /// rate.
    /// </summary>
    HighQuality = 2,
}

/// <summary>
/// Control to report the current AWB algorithm state. Currently identical
/// to ANDROID_CONTROL_AWB_STATE.
/// </summary>
/// <remarks>
/// Current state of the AWB algorithm.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum AwbState : int
{
    /// <summary>
    /// The AWB algorithm is inactive.
    /// </summary>
    Inactive = 0,
    /// <summary>
    /// The AWB algorithm has not converged yet.
    /// </summary>
    Searching = 1,
    /// <summary>
    /// The AWB algorithm has converged.
    /// </summary>
    Converged = 2,
    /// <summary>
    /// The AWB algorithm is locked.
    /// </summary>
    Locked = 3,
}

/// <summary>
/// Control to report if the lens shading map is available. Currently
/// identical to ANDROID_STATISTICS_LENS_SHADING_MAP_MODE.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum LensShadingMapMode : int
{
    /// <summary>
    /// No lens shading map mode is available.
    /// </summary>
    Off = 0,
    /// <summary>
    /// The lens shading map mode is available.
    /// </summary>
    On = 1,
}

/// <summary>
/// Control to select the test pattern mode. Currently identical to
/// ANDROID_SENSOR_TEST_PATTERN_MODE.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum TestPatternMode : int
{
    /// <summary>
    /// No test pattern mode is used. The camera device returns frames from
    /// the image sensor.
    /// </summary>
    Off = 0,
    /// <summary>
    /// Each pixel in [R, G_even, G_odd, B] is replaced by its respective
    /// color channel provided in test pattern data.
    /// \todo Add control for test pattern data.
    /// </summary>
    SolidColor = 1,
    /// <summary>
    /// All pixel data is replaced with an 8-bar color pattern. The vertical
    /// bars (left-to-right) are as follows; white, yellow, cyan, green,
    /// magenta, red, blue and black. Each bar should take up 1/8 of the
    /// sensor pixel array width. When this is not possible, the bar size
    /// should be rounded down to the nearest integer and the pattern can
    /// repeat on the right side. Each bar's height must always take up the
    /// full sensor pixel array height.
    /// </summary>
    ColorBars = 2,
    /// <summary>
    /// The test pattern is similar to TestPatternModeColorBars,
    /// except that each bar should start at its specified color at the top
    /// and fade to gray at the bottom. Furthermore each bar is further
    /// subdevided into a left and right half. The left half should have a
    /// smooth gradient, and the right half should have a quantized
    /// gradient. In particular, the right half's should consist of blocks
    /// of the same color for 1/16th active sensor pixel array width. The
    /// least significant bits in the quantized gradient should be copied
    /// from the most significant bits of the smooth gradient. The height of
    /// each bar should always be a multiple of 128. When this is not the
    /// case, the pattern should repeat at the bottom of the image.
    /// </summary>
    ColorBarsFadeToGray = 3,
    /// <summary>
    /// All pixel data is replaced by a pseudo-random sequence generated
    /// from a PN9 512-bit sequence (typically implemented in hardware with
    /// a linear feedback shift register). The generator should be reset at
    /// the beginning of each frame, and thus each subsequent raw frame with
    /// this test pattern should be exactly the same as the last.
    /// </summary>
    Pn9 = 4,
    /// <summary>
    /// The first custom test pattern. All custom patterns that are
    /// available only on this camera device are at least this numeric
    /// value. All of the custom test patterns will be static (that is the
    /// raw image must not vary from frame to frame).
    /// </summary>
    Custom1 = 256,
}

/// <summary>
/// Control to select the face detection mode used by the pipeline.
/// </summary>
/// <remarks>
/// Currently identical to ANDROID_STATISTICS_FACE_DETECT_MODE.
/// <para/>
/// See also: FaceDetectFaceRectangles.
/// See also: FaceDetectFaceScores.
/// See also: FaceDetectFaceLandmarks.
/// See also: FaceDetectFaceIds.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum FaceDetectMode : int
{
    /// <summary>
    /// Pipeline doesn't perform face detection and doesn't report any
    /// control related to face detection.
    /// </summary>
    Off = 0,
    /// <summary>
    /// Pipeline performs face detection and reports the
    /// FaceDetectFaceRectangles and FaceDetectFaceScores controls for each
    /// detected face. FaceDetectFaceLandmarks and FaceDetectFaceIds are
    /// optional.
    /// </summary>
    Simple = 1,
    /// <summary>
    /// Pipeline performs face detection and reports all the controls
    /// related to face detection including FaceDetectFaceRectangles,
    /// FaceDetectFaceScores, FaceDetectFaceLandmarks, and
    /// FaceDeteceFaceIds for each detected face.
    /// </summary>
    Full = 2,
}

/// <summary>
/// Enable or disable camera synchronisation ("sync") mode.
/// </summary>
/// <remarks>
/// When sync mode is enabled, a camera will synchronise frames temporally
/// with other cameras, either attached to the same device or a different
/// one. There should be one "server" device, which broadcasts timing
/// information to one or more "clients". Communication is one-way, from
/// server to clients only, and it is only clients that adjust their frame
/// timings to match the server.
/// <para/>
/// Sync mode requires all cameras to be running at (as far as possible) the
/// same fixed framerate. Clients may continue to make adjustments to keep
/// their cameras synchronised with the server for the duration of the
/// session, though any updates after the initial ones should remain small.
/// <para/>
/// See also: SyncReady.
/// See also: SyncTimer.
/// See also: SyncFrames.
/// </remarks>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum SyncMode : int
{
    /// <summary>
    /// Disable sync mode.
    /// </summary>
    Off = 0,
    /// <summary>
    /// Enable sync mode, act as server. The server broadcasts timing
    /// messages to any clients that are listening, so that the clients can
    /// synchronise their camera frames with the server's.
    /// </summary>
    Server = 1,
    /// <summary>
    /// Enable sync mode, act as client. A client listens for any server
    /// messages, and arranges for its camera frames to synchronise as
    /// closely as possible with the server's. Many clients can listen out
    /// for the same server. Clients can also be started ahead of any
    /// servers, causing them merely to wait for the server to start.
    /// </summary>
    Client = 2,
}

/// <summary>
/// Camera mounting location
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum Location : int
{
    /// <summary>
    /// The camera is mounted on the front side of the device, facing the
    /// user
    /// </summary>
    Front = 0,
    /// <summary>
    /// The camera is mounted on the back side of the device, facing away
    /// from the user
    /// </summary>
    Back = 1,
    /// <summary>
    /// The camera is attached to the device in a way that allows it to
    /// be moved freely
    /// </summary>
    External = 2,
}

/// <summary>
/// The arrangement of color filters on sensor; represents the colors in the
/// top-left 2x2 section of the sensor, in reading order. Currently
/// identical to ANDROID_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("src/LibcameraSharp.Core/Generate/gen_controls.py", "0.7.2+rpt20260817")]
public enum ColorFilterArrangement : int
{
    /// <summary>
    /// RGGB Bayer pattern
    /// </summary>
    RGGB = 0,
    /// <summary>
    /// GRBG Bayer pattern
    /// </summary>
    GRBG = 1,
    /// <summary>
    /// GBRG Bayer pattern
    /// </summary>
    GBRG = 2,
    /// <summary>
    /// BGGR Bayer pattern
    /// </summary>
    BGGR = 3,
    /// <summary>
    /// Sensor is not Bayer; output has 3 16-bit values for each pixel,
    /// instead of just 1 16-bit value per pixel.
    /// </summary>
    RGB = 4,
    /// <summary>
    /// Sensor is not Bayer; output consists of a single colour channel.
    /// </summary>
    MONO = 5,
}
