###########################################################
#                                                         #
#   TL;DR: Only makes a new "GitHub Releases"             #
#   for changelog purpose. Nothing else.                  #
#   - Automatically triggered on pushes to main branch.   #
#                                                         #
###########################################################

name: Continuous Release | LibcameraSharp Package
permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout 📥
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Setup .NET 👨🏽‍💻
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
        with:
          dotnet-version: 10.x

      - name: Extract Package Version 📌
        id: version
        run: echo "package_version=$(dotnet msbuild src/LibcameraSharp/LibcameraSharp.csproj -getProperty:Version)" >> $GITHUB_OUTPUT

      - name: Create Release 🚀
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2
        with:
          name: LibcameraSharp v${{ steps.version.outputs.package_version }}.${{ github.run_number }}
          tag_name: v${{ steps.version.outputs.package_version }}.${{ github.run_number }}
          prerelease: false
          make_latest: true
          generate_release_notes: true
